import type { RiskLevel } from "./founder-governance/policy";
import type { MaintenanceActionCode, MaintenanceScopeType, ModuleCode, SnapshotType, TargetEntityType } from "./platform-ops";

export type ActionScopeLevel = "system" | "firm" | "module" | "record";

export type FounderActionRegistryItem = {
  action_code: MaintenanceActionCode;
  label: string;
  description: string;
  scope_level: ActionScopeLevel;
  scope_type: MaintenanceScopeType;
  module_code?: ModuleCode;
  target_entity_type?: TargetEntityType;
  risk_level: RiskLevel;
  requires_snapshot: boolean;
  supports_preview: boolean;
  supports_execute: boolean;
  restore_available: boolean;
  recommended_snapshot_type?: SnapshotType;
};

export const FOUNDER_ACTION_REGISTRY: FounderActionRegistryItem[] = [
  {
    action_code: "recalculate_stats",
    label: "Recalculate statistics",
    description: "Recompute key counts used in dashboards and summaries.",
    scope_level: "firm",
    scope_type: "firm",
    risk_level: "low",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: false,
  },
  {
    action_code: "rebuild_reports",
    label: "Rebuild dashboard cache",
    description: "Rebuilds firm dashboard stats cache to reduce load and improve dashboard responsiveness.",
    scope_level: "firm",
    scope_type: "firm",
    risk_level: "medium",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: false,
  },
  {
    action_code: "reindex_documents",
    label: "Reindex documents checklist metadata",
    description: "Resets derived checklist/applicability metadata so it can be recomputed safely.",
    scope_level: "module",
    scope_type: "module",
    module_code: "documents",
    risk_level: "medium",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: false,
  },
  {
    action_code: "clear_failed_jobs",
    label: "Clear failed document jobs",
    description: "Archives failed document batch/extraction jobs for this firm (metadata is preserved).",
    scope_level: "firm",
    scope_type: "firm",
    risk_level: "low",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: false,
  },
  {
    action_code: "force_logout_sessions",
    label: "Force logout all firm sessions",
    description: "Invalidates all active sessions for users in this firm.",
    scope_level: "firm",
    scope_type: "firm",
    risk_level: "medium",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: false,
  },
  {
    action_code: "repair_derived_data",
    label: "Repair derived document links",
    description: "Repairs orphaned checklist links that reference missing uploads.",
    scope_level: "module",
    scope_type: "module",
    module_code: "documents",
    risk_level: "medium",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: false,
  },
  {
    action_code: "reset_settings_default",
    label: "Reset settings to default",
    description: "Resets firm settings fields and clears bank accounts. Pre-action snapshot required.",
    scope_level: "firm",
    scope_type: "settings",
    module_code: "settings",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "settings",
  },
  {
    action_code: "reset_settings_last_snapshot",
    label: "Reset settings to last snapshot",
    description: "Restores settings from the most recent settings snapshot for the firm.",
    scope_level: "firm",
    scope_type: "settings",
    module_code: "settings",
    risk_level: "high",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "settings",
  },
  {
    action_code: "reset_projects_module",
    label: "Reset projects module",
    description: "Archives all projects if no active cases exist. Pre-action snapshot required.",
    scope_level: "module",
    scope_type: "module",
    module_code: "projects",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "module",
  },
  {
    action_code: "reset_developers_module",
    label: "Reset developers module",
    description: "Clears developers module derived data for the firm. Pre-action snapshot required.",
    scope_level: "module",
    scope_type: "module",
    module_code: "developers",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "module",
  },
  {
    action_code: "reset_reports_module",
    label: "Reset reports module",
    description: "Clears reports module derived data for the firm. Pre-action snapshot required.",
    scope_level: "module",
    scope_type: "module",
    module_code: "reports",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "module",
  },
  {
    action_code: "reset_documents_metadata",
    label: "Reset documents metadata",
    description: "Resets documents metadata and derived indices. Pre-action snapshot required.",
    scope_level: "module",
    scope_type: "module",
    module_code: "documents",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "module",
  },
  {
    action_code: "reset_communications_sync",
    label: "Reset communications sync",
    description: "Resets communications sync state for this firm. Pre-action snapshot required.",
    scope_level: "module",
    scope_type: "module",
    module_code: "communications",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "module",
  },
  {
    action_code: "reset_case_workflow",
    label: "Reset case workflow/status",
    description: "Keeps the base case record, resets workflow steps to pending.",
    scope_level: "record",
    scope_type: "record",
    target_entity_type: "case",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "record",
  },
  {
    action_code: "reset_case_generated_docs",
    label: "Reset case generated documents",
    description: "Archives generated case documents and soft-deletes workflow uploads.",
    scope_level: "record",
    scope_type: "record",
    target_entity_type: "case",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "record",
  },
  {
    action_code: "reset_case_progress_metadata",
    label: "Reset case progress metadata",
    description: "Clears workflow completion and key date progress fields.",
    scope_level: "record",
    scope_type: "record",
    target_entity_type: "case",
    risk_level: "high",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "record",
  },
  {
    action_code: "reset_case_full_soft",
    label: "Full soft reset (initial state)",
    description: "Resets workflow, generated outputs, and progress metadata. Snapshot required.",
    scope_level: "record",
    scope_type: "record",
    target_entity_type: "case",
    risk_level: "critical",
    requires_snapshot: true,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
    recommended_snapshot_type: "record",
  },
  {
    action_code: "restore_snapshot",
    label: "Restore from snapshot",
    description: "Applies a previously created snapshot back onto the firm/module/record scope.",
    scope_level: "firm",
    scope_type: "settings",
    risk_level: "high",
    requires_snapshot: false,
    supports_preview: true,
    supports_execute: true,
    restore_available: true,
  },
];

export type FounderRestoreOperationRegistryItem = {
  operation_code: "restore_snapshot" | "rollback_restore";
  label: string;
  description: string;
  risk_level: RiskLevel;
  supports_preview: boolean;
  supports_execute: boolean;
};

export const FOUNDER_RESTORE_OPERATION_REGISTRY: FounderRestoreOperationRegistryItem[] = [
  {
    operation_code: "restore_snapshot",
    label: "Restore from snapshot",
    description: "Applies a snapshot payload onto the current state for the selected scope.",
    risk_level: "high",
    supports_preview: true,
    supports_execute: true,
  },
  {
    operation_code: "rollback_restore",
    label: "Rollback (undo restore)",
    description: "Rolls back a completed restore by applying the recorded pre-restore snapshot. Always treated as critical.",
    risk_level: "critical",
    supports_preview: true,
    supports_execute: true,
  },
];
