import express, { type Router as ExpressRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import platformRouter from "./platform.js";
import usersRouter from "./users.js";
import rolesRouter from "./roles.js";
import developersRouter from "./developers.js";
import projectsRouter from "./projects.js";
import clientsRouter from "./clients.js";
import casesRouter from "./cases.js";
import caseFilesRouter from "./case-files.js";
import dashboardRouter from "./dashboard.js";
import storageRouter from "./storage.js";
import documentsRouter from "./documents.js";
import accountingRouter from "./accounting.js";
import communicationsRouter from "./communications.js";
import reportsRouter from "./reports.js";
import auditRouter from "./audit.js";
import hubRouter from "./hub.js";
import quotationsRouter from "./quotations.js";
import firmSettingsRouter from "./firm-settings.js";
import regulatoryRouter from "./regulatory.js";
import invoicesRouter from "./invoices.js";
import receiptsRouter from "./receipts.js";
import paymentVouchersRouter from "./payment-vouchers.js";
import timeEntriesRouter from "./time-entries.js";
import caseTasksRouter from "./case-tasks.js";
import complianceReportsRouter from "./compliance-reports.js";
import supportSessionsRouter from "./support-sessions.js";
import partiesRouter from "./parties.js";
import complianceRouter from "./compliance.js";
import conflictRouter from "./conflict.js";
import platformOpsRouter from "./platform-ops.js";
import platformApprovalsRouter from "./platform-approvals.js";
import platformOpsCenterRouter from "./platform-ops-center.js";

type RouterLike = {
  use: (...args: unknown[]) => RouterLike;
};

const expressRouter = express.Router();
const routerInternal = expressRouter as unknown as RouterLike;

routerInternal.use(healthRouter);
routerInternal.use(authRouter);
routerInternal.use(platformRouter);
routerInternal.use(usersRouter);
routerInternal.use(rolesRouter);
routerInternal.use(developersRouter);
routerInternal.use(projectsRouter);
routerInternal.use(clientsRouter);
routerInternal.use(casesRouter);
routerInternal.use(caseFilesRouter);
routerInternal.use(dashboardRouter);
routerInternal.use(storageRouter);
routerInternal.use(documentsRouter);
routerInternal.use(accountingRouter);
routerInternal.use(communicationsRouter);
routerInternal.use(reportsRouter);
routerInternal.use(auditRouter);
routerInternal.use(platformOpsRouter);
routerInternal.use(platformApprovalsRouter);
routerInternal.use(platformOpsCenterRouter);
routerInternal.use(hubRouter);
routerInternal.use(quotationsRouter);
routerInternal.use(firmSettingsRouter);
routerInternal.use(regulatoryRouter);
routerInternal.use(invoicesRouter);
routerInternal.use(receiptsRouter);
routerInternal.use(paymentVouchersRouter);
routerInternal.use(timeEntriesRouter);
routerInternal.use(caseTasksRouter);
routerInternal.use(complianceReportsRouter);
routerInternal.use(supportSessionsRouter);
routerInternal.use(partiesRouter);
routerInternal.use(complianceRouter);
routerInternal.use(conflictRouter);

const exportedRouter = expressRouter as unknown as ExpressRouter;
export { exportedRouter as router };
export default exportedRouter;
