import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import platformRouter from "./platform";
import usersRouter from "./users";
import rolesRouter from "./roles";
import developersRouter from "./developers";
import projectsRouter from "./projects";
import clientsRouter from "./clients";
import casesRouter from "./cases";
import caseFilesRouter from "./case-files";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import documentsRouter from "./documents";
import accountingRouter from "./accounting";
import communicationsRouter from "./communications";
import reportsRouter from "./reports";
import auditRouter from "./audit";
import hubRouter from "./hub";
import quotationsRouter from "./quotations";
import firmSettingsRouter from "./firm-settings";
import regulatoryRouter from "./regulatory";
import invoicesRouter from "./invoices";
import receiptsRouter from "./receipts";
import paymentVouchersRouter from "./payment-vouchers";
import timeEntriesRouter from "./time-entries";
import caseTasksRouter from "./case-tasks";
import complianceReportsRouter from "./compliance-reports";
import supportSessionsRouter from "./support-sessions";
import partiesRouter from "./parties";
import complianceRouter from "./compliance";
import conflictRouter from "./conflict";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(platformRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(developersRouter);
router.use(projectsRouter);
router.use(clientsRouter);
router.use(casesRouter);
router.use(caseFilesRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(documentsRouter);
router.use(accountingRouter);
router.use(communicationsRouter);
router.use(reportsRouter);
router.use(auditRouter);
router.use(hubRouter);
router.use(quotationsRouter);
router.use(firmSettingsRouter);
router.use(regulatoryRouter);
router.use(invoicesRouter);
router.use(receiptsRouter);
router.use(paymentVouchersRouter);
router.use(timeEntriesRouter);
router.use(caseTasksRouter);
router.use(complianceReportsRouter);
router.use(supportSessionsRouter);
router.use(partiesRouter);
router.use(complianceRouter);
router.use(conflictRouter);

export default router;
