-- Migration 0151: Canonical FEATURE_REGISTRY ↔ platform_features parity patch.
-- Generated programmatically from lib/db/src/feature-registry.ts FEATURE_REGISTRY.
--
-- Architecture (Option A Conservative / NO DB schema expansion):
--   Canonical FEATURE_REGISTRY
--   ├── persisted DB projection (platform_features: 13 fields)
--   │     feature_key, name, module, parent_feature_key, value_type, default_value,
--   │     configurable, founder_only, dependency_json, route_hint, description,
--   │     sort_order, status
--   └── runtime-only canonical metadata (never persisted to platform_features):
--         backendGuardKey, planControlled, firmControlledOverride, jobGuards
--         (enforced at runtime via applyCanonicalSafetyCeiling / collectJobGuardToFeatureMap / assertFirmOverrideAllowed)
--
-- Idempotent behavior:
--   1) INSERT every canonical feature row with full 13 persisted-field attributes.
--   2) ON CONFLICT (feature_key) DO UPDATE SET every persisted attribute = EXCLUDED,
--      including default_value, description, sort_order (columns 0150 DO UPDATE SET
--      historically omitted → this migration corrects stale mirror rows).
--   3) updated_at = now() whenever any correction occurs.

WITH canonical(feature_key, name, module, parent_feature_key, value_type, default_value, configurable, founder_only, dependency_json, route_hint, description, sort_order, status) AS (
  VALUES
    ('module.dashboard', 'Dashboard (all firm dashboards)', 'dashboard', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', 'Top-level dashboard feature module. If OFF, no dashboard pages visible.', 0, 'active'),
    ('dashboard.firm', 'Firm Dashboard', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', NULL, 0, 'active'),
    ('dashboard.partner', 'Partner Dashboard', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', NULL, 0, 'active'),
    ('dashboard.management', 'Management Dashboard', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', NULL, 0, 'active'),
    ('dashboard.workbench', 'My Work / Workbench', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/workbench', NULL, 0, 'active'),
    ('dashboard.kpi', 'KPI Widgets', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', NULL, 0, 'active'),
    ('dashboard.approvals', 'Pending Approvals Widget', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', NULL, 0, 'active'),
    ('dashboard.alerts', 'Alerts / Escalations Widget', 'dashboard', 'module.dashboard', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/dashboard', NULL, 0, 'active'),
    ('module.cases', 'Cases', 'cases', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.read', 'View / Search / Archive Cases', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.create', 'Create New Case', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.legacy_import', 'Legacy Excel Import (Historical Cases)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.overview', 'Case Overview Tab', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases/:id', NULL, 0, 'active'),
    ('cases.parties', 'Parties Tab (purchasers/borrowers/vendors)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.property', 'Property Info Tab', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.loan', 'Loan Info Tab', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.reference', 'Reference Numbers + History + Suggestions', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.tasks', 'Case Tasks', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases/:id/tasks', NULL, 0, 'active'),
    ('cases.timeline', 'Case Timeline', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.documents', 'Case Documents Tab', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '["module.documents"]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.supporting_documents', 'Case Supporting Documents Tab', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '["module.documents"]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.notes', 'Case Notes', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.assignment', 'Case Assignment + Bulk Assign', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.approval', 'Case Approval (approve/reject/resubmit)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.amendment', 'Case Amendment / Edit key fields', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.key_dates', 'Key Dates / Milestones', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.workflow', 'Workflow Steps + Attachments', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.batch_update', 'Batch Update (cases)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.batch_print', 'Batch Print (case documents)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.developer_sales', 'Developer Sales Cases (perfection)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.subsale', 'Subsale Cases', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.perfection', 'Perfection Steps', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.intake', 'Intake Inbox', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases/intake', NULL, 0, 'active'),
    ('cases.conflict_check', 'Conflict Check', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '["module.cases"]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.monitor', 'Case Monitor (SLAs)', 'cases', 'module.cases', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('cases.export', 'Case Export (CSV)', 'cases', 'cases.read', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('limit.cases.max', 'Max Active Cases', 'cases', 'module.cases', 'integer', '-1'::jsonb, true, false, '[]'::jsonb, '/app/cases', '-1 = unlimited', 0, 'active'),
    ('limit.cases.monthly_new', 'Max New Cases/Month', 'cases', 'module.cases', 'integer', '-1'::jsonb, true, false, '[]'::jsonb, '/app/cases', NULL, 0, 'active'),
    ('module.developers', 'Developers', 'developers', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/developers', NULL, 0, 'active'),
    ('developers.read', 'View Developers', 'developers', 'module.developers', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/developers', NULL, 0, 'active'),
    ('developers.create', 'Create Developer', 'developers', 'module.developers', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/developers', NULL, 0, 'active'),
    ('developers.edit', 'Edit Developer', 'developers', 'module.developers', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/developers', NULL, 0, 'active'),
    ('developers.codes', 'Developer/Project Codes Config', 'developers', 'module.developers', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/developers', NULL, 0, 'active'),
    ('module.projects', 'Projects', 'projects', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.read', 'View Projects', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.create', 'Create Project', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.edit', 'Edit Project', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.phases', 'Phases Management', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.units', 'Units/Lots Management', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.reference_config', 'Reference Configuration', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('projects.hims_mapping', 'HIMS Mapping', 'projects', 'module.projects', 'boolean', 'true'::jsonb, true, false, '["module.hims"]'::jsonb, '/app/projects', NULL, 0, 'active'),
    ('module.documents', 'Documents & Automation Hub', 'documents', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.hub', 'Automation Hub', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents/automation', NULL, 0, 'active'),
    ('documents.templates', 'Template Library', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents/variables', NULL, 0, 'active'),
    ('documents.templates.founder', 'Founder Templates', 'documents', 'documents.templates', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.templates.firm', 'Firm Templates', 'documents', 'documents.templates', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.word', 'Word Generation', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.pdf', 'PDF Generation + Mapping', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.variables', 'Variables / Custom Variables', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents/variables', NULL, 0, 'active'),
    ('documents.batch', 'Batch Generation', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.generated', 'Generated Documents (case/workflow)', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.versioning', 'History / Versioning', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.ocr', 'OCR', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '["module.ai"]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.ai_read', 'AI Reading + Date Extraction', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '["module.ai"]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.ai_migration', 'AI Template Migration', 'documents', 'documents.templates', 'boolean', 'true'::jsonb, true, false, '["module.ai"]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('documents.logs', 'Generation Logs', 'documents', 'module.documents', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/documents/generation-logs', NULL, 0, 'active'),
    ('limit.documents.generation_monthly', 'Max Generated Docs/Month', 'documents', 'module.documents', 'integer', '-1'::jsonb, true, false, '[]'::jsonb, '/app/documents', NULL, 0, 'active'),
    ('module.accounting', 'Accounting', 'accounting', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.dashboard', 'Accounting Dashboard', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.quotation', 'Quotation', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.invoice', 'Invoice (issue/view)', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.receipt', 'Receipt', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.payment_voucher', 'Payment Voucher (PV)', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.payment_voucher.create', 'Create PV', 'accounting', 'accounting.payment_voucher', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.payment_voucher.submit', 'Submit PV', 'accounting', 'accounting.payment_voucher', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.payment_voucher.approval', 'PV Approval', 'accounting', 'accounting.payment_voucher', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.file_listing', 'File Listing', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.client_ledger', 'Client Ledger', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.case_ledger', 'Case Ledger', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.office_ledger', 'Office Ledger', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.trust_account', 'Trust Account', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.trust_statement', 'Trust Statement', 'accounting', 'accounting.trust_account', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.stakeholder', 'Stakeholder', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.disbursement', 'Disbursement', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.professional_fees', 'Professional Fees', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.travelling', 'Travelling', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.miscellaneous', 'Miscellaneous', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.overcollection', 'Overcollection', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.office_income', 'Office Income', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.bank_transaction', 'Bank Transaction', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.bank_reconciliation', 'Bank Reconciliation', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.payment', 'Payment (out)', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.refund', 'Refund', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.reports', 'Accounting Reports', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '["module.reports"]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.approvals', 'Accounting Approvals', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('accounting.notifications', 'Accounting Notifications', 'accounting', 'module.accounting', 'boolean', 'true'::jsonb, true, false, '["module.notifications"]'::jsonb, '/app/accounting', NULL, 0, 'active'),
    ('module.einvoice', 'E-Invoice (LHDN)', 'einvoice', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.individual', 'Individual E-Invoice', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.consolidated', 'Consolidated E-Invoice', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.submit', 'Submit to LHDN', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.status', 'Status & History', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.credit_note', 'Credit Note', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.debit_note', 'Debit Note', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.refund_note', 'Refund Note', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.validation', 'Validation', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.lhdn_integration', 'LHDN Integration', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('einvoice.logs', 'Logs', 'einvoice', 'module.einvoice', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.communications', 'Communications', 'communications', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email', 'Email Control', 'communications', 'module.communications', 'boolean', 'false'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', 'Future phase feature. Temporarily disabled until Email Control is production ready.', 0, 'inactive'),
    ('communications.email.settings', 'Email Settings', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.m365', 'Microsoft 365', 'communications', 'communications.email.settings', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.imap', 'IMAP', 'communications', 'communications.email.settings', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.gmail', 'Gmail', 'communications', 'communications.email.settings', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.folders', 'Inbox/Sent/Draft/Archive', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.mark_read', 'Read/Unread', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.reply', 'Reply / Reply All', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.forward', 'Forward', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.remarks', 'Remarks', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.assign_user', 'Assign User', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.link_case', 'Link to Case', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '["module.cases"]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.search', 'Search / Filter', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.sla', 'SLA Tracking', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.task', 'Email → Task', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '["cases.tasks"]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.sync', 'Sync', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.email.logs', 'Logs', 'communications', 'communications.email', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/communication/email', NULL, 0, 'active'),
    ('communications.whatsapp', 'WhatsApp Inbox', 'communications', 'module.communications', 'boolean', 'false'::jsonb, true, false, '[]'::jsonb, '/app/communication/whatsapp', 'Future phase feature. Temporarily disabled until WhatsApp integration is production ready.', 0, 'inactive'),
    ('communications.hub', 'Hub Unified', 'communications', 'module.communications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hub', NULL, 0, 'active'),
    ('module.hr', 'Human Resources (HRMS)', 'hr', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hr.dashboard', 'HR Dashboard', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/dashboard', NULL, 0, 'active'),
    ('hr.employees', 'Employees', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/employees', NULL, 0, 'active'),
    ('hr.departments', 'Departments', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/departments', NULL, 0, 'active'),
    ('hr.positions', 'Positions', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/positions', NULL, 0, 'active'),
    ('hr.attendance', 'Attendance', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/attendance', NULL, 0, 'active'),
    ('hr.leave', 'Leave', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/leave', NULL, 0, 'active'),
    ('hr.claims', 'Claims', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/claims', NULL, 0, 'active'),
    ('hr.payroll', 'Payroll', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/payroll', NULL, 0, 'active'),
    ('hr.onboarding', 'Onboarding', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/onboarding', NULL, 0, 'active'),
    ('hr.offboarding', 'Offboarding', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/offboarding', NULL, 0, 'active'),
    ('hr.recruitment', 'Recruitment', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/recruitment', NULL, 0, 'active'),
    ('hr.performance', 'Performance', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/performance', NULL, 0, 'active'),
    ('hr.training', 'Training', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/training', NULL, 0, 'active'),
    ('hr.assets', 'Assets', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/assets', NULL, 0, 'active'),
    ('hr.documents', 'HR Documents', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/documents', NULL, 0, 'active'),
    ('hr.notifications', 'HR Notifications', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '["module.notifications"]'::jsonb, NULL, NULL, 0, 'active'),
    ('hr.approvals', 'HR Approvals (leave/claims/payroll)', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hr.self_service', 'Employee Self Service', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hr.reports', 'HR Reports', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '["module.reports"]'::jsonb, '/app/hr/reports', NULL, 0, 'active'),
    ('hr.settings', 'HR Settings', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/hr/settings', NULL, 0, 'active'),
    ('hr.integration_events', 'HR Integration Events (webhooks)', 'hr', 'module.hr', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.rbac', 'User & Role Management', 'rbac', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('rbac.users', 'Users (list/edit)', 'rbac', 'module.rbac', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/users', NULL, 0, 'active'),
    ('rbac.users.create', 'Create/Invite Users', 'rbac', 'rbac.users', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('rbac.users.invitations', 'Invitations', 'rbac', 'rbac.users', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('rbac.users.assignments', 'Assignments (to cases/dept)', 'rbac', 'rbac.users', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('rbac.users.initials', 'Initials Config', 'rbac', 'rbac.users', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('rbac.roles', 'Roles', 'rbac', 'module.rbac', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/roles', NULL, 0, 'active'),
    ('rbac.permissions', 'Permissions', 'rbac', 'rbac.roles', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('rbac.departments', 'Departments (firm)', 'rbac', 'module.rbac', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('limit.users.max', 'Max Users', 'rbac', 'module.rbac', 'integer', '10'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.contacts', 'Contacts (Clients / Parties)', 'contacts', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('contacts.clients', 'Clients', 'contacts', 'module.contacts', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/clients', NULL, 0, 'active'),
    ('contacts.borrowers', 'Purchasers / Borrowers', 'contacts', 'module.contacts', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('contacts.vendors', 'Vendors', 'contacts', 'module.contacts', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('contacts.banks', 'Banks', 'contacts', 'module.contacts', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('contacts.developers_contact', 'Developer Contacts', 'contacts', 'module.contacts', 'boolean', 'true'::jsonb, true, false, '["module.developers"]'::jsonb, NULL, NULL, 0, 'active'),
    ('contacts.other_parties', 'Other Parties', 'contacts', 'module.contacts', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.notifications', 'Notifications', 'notifications', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.in_app', 'In-App Notifications', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.red_dot', 'Red Dot / Unread Count Badge', 'notifications', 'notifications.in_app', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.approval', 'Approval Notifications', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.case', 'Case Notifications', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.accounting', 'Accounting Notifications', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.pv_escalation', 'PV Escalation', 'notifications', 'notifications.accounting', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.lawyer', 'Lawyer Notifications', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.manager', 'Manager Notifications', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('notifications.partner_escalation', 'Partner Escalation', 'notifications', 'module.notifications', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.hims', 'HIMS / eSPA Tracker', 'hims', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.tracker', 'HIMS Status Tracker', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.credentials', 'Developer Credentials / Config', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.project_mapping', 'Project / Phase Mapping', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '["module.projects"]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.unit_lot_title', 'Unit/Lot/Title Mapping', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.espa_status', 'eSPA Status', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.spa_tracker', 'SPA Tracker', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.spa_stamped_handover', 'SPA Stamped Handover', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.status_check', 'Status Check (api)', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.compare_lawcaspro_hims', 'Compare Lawcaspro ↔ HIMS', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.compare_lawcaspro_ekyc', 'Compare Lawcaspro ↔ eKYC', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '["module.ekyc"]'::jsonb, NULL, NULL, 0, 'active'),
    ('hims.notifications', 'HIMS Notifications', 'hims', 'module.hims', 'boolean', 'true'::jsonb, true, false, '["module.notifications"]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.ekyc', 'eKYC / Identity Verification', 'ekyc', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ekyc.verify', 'Identity Verification', 'ekyc', 'module.ekyc', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ekyc.status', 'Status Overview', 'ekyc', 'module.ekyc', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ekyc.comparison', 'Comparison (HIMS/others)', 'ekyc', 'module.ekyc', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ekyc.history', 'History', 'ekyc', 'module.ekyc', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.reports', 'Reports', 'reports', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.case', 'Case Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '["module.cases"]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.accounting', 'Accounting Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '["module.accounting"]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.hr', 'HR Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '["module.hr"]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.management', 'Management Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.status', 'Status Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.productivity', 'Productivity Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.audit', 'Audit Reports', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '["module.audit"]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.export_pdf', 'PDF Export', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('reports.export_excel', 'Excel Export', 'reports', 'module.reports', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/reports', NULL, 0, 'active'),
    ('module.settings', 'Settings (Firm)', 'settings', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.firm', 'Firm Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.case', 'Case Settings / Types / Config', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.cases"]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.reference', 'Reference Number Config', 'settings', 'settings.case', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.accounting', 'Accounting Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.accounting"]'::jsonb, '/app/settings/accounting', NULL, 0, 'active'),
    ('settings.hr', 'HR Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.hr"]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.email', 'Email Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.communications"]'::jsonb, '/app/settings/email', NULL, 0, 'active'),
    ('settings.document', 'Document / Templates Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.documents"]'::jsonb, '/app/settings/templates', NULL, 0, 'active'),
    ('settings.notifications', 'Notification Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.notifications"]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.integrations', 'Integrations Settings', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.subscription', 'Subscription & Billing (Firm view)', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/settings', NULL, 0, 'active'),
    ('settings.logs', 'Logs (firm)', 'settings', 'module.settings', 'boolean', 'true'::jsonb, true, false, '["module.audit"]'::jsonb, '/app/settings/logs', NULL, 0, 'active'),
    ('module.storage', 'Storage / File Custody', 'storage', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('storage.file_custody', 'File Custody Registry (Phase 2/3 candidate)', 'storage', 'module.storage', 'boolean', 'false'::jsonb, true, false, '[]'::jsonb, '/app/file-custody', 'Future: Phase 2/3 candidate. Default disabled for all firms; currently hidden from navigation and route-gated.', 0, 'inactive'),
    ('storage.uploads', 'General File Uploads', 'storage', 'module.storage', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('limit.storage.gb', 'Storage (GB)', 'storage', 'module.storage', 'integer', '100'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.ai', 'AI & OCR Capabilities', 'ai', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ai.ocr', 'OCR Engine', 'ai', 'module.ai', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ai.draft', 'AI Drafting Assistant', 'ai', 'module.ai', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('ai.reading', 'AI Reading / Extraction', 'ai', 'module.ai', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('limit.ai.ocr_pages_monthly', 'OCR Pages / Month', 'ai', 'module.ai', 'integer', '1000'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('limit.ai.draft_tokens_monthly', 'AI Draft Tokens / Month', 'ai', 'module.ai', 'integer', '-1'::jsonb, true, false, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('module.audit', 'Audit Logs', 'audit', NULL, 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/audit-logs', NULL, 0, 'active'),
    ('audit.logs', 'View Audit Logs', 'audit', 'module.audit', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/audit-logs', NULL, 0, 'active'),
    ('audit.export', 'Export Audit Logs', 'audit', 'module.audit', 'boolean', 'true'::jsonb, true, false, '[]'::jsonb, '/app/audit-logs', NULL, 0, 'active'),
    ('module.platform', 'Platform Admin (Founder)', 'platform', NULL, 'boolean', 'true'::jsonb, false, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.firms', 'Firms Management', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.plans', 'Plans & Entitlements', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.billing', 'Billing & Ledger (founder view)', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.audit', 'Cross-Firm Audit', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.ops_center', 'Ops Center', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.approvals', 'Platform Approvals', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.support_sessions', 'Support Sessions (consent-based access)', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.incident_center', 'Incident Center', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active'),
    ('platform.governance', 'Governance', 'platform', 'module.platform', 'boolean', 'true'::jsonb, true, true, '[]'::jsonb, NULL, NULL, 0, 'active')

)
, upserted AS (
  INSERT INTO platform_features (
    feature_key, name, module, parent_feature_key, value_type, default_value,
    configurable, founder_only, dependency_json, route_hint, description,
    sort_order, status, created_at, updated_at
  )
  SELECT
    c.feature_key, c.name, c.module, c.parent_feature_key, c.value_type, c.default_value,
    c.configurable, c.founder_only, c.dependency_json, c.route_hint, c.description,
    c.sort_order, c.status, now(), now()
  FROM canonical c
  ON CONFLICT (feature_key) DO UPDATE SET
    name = EXCLUDED.name,
    module = EXCLUDED.module,
    parent_feature_key = EXCLUDED.parent_feature_key,
    value_type = EXCLUDED.value_type,
    default_value = EXCLUDED.default_value,
    configurable = EXCLUDED.configurable,
    founder_only = EXCLUDED.founder_only,
    dependency_json = EXCLUDED.dependency_json,
    route_hint = EXCLUDED.route_hint,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    status = EXCLUDED.status,
    updated_at = now()
  RETURNING feature_key
)
SELECT count(*) AS rows_upserted FROM upserted;
