-- 0156: Template Migration Proposals (PART3 3B)
-- doc_template_migration_runs + doc_template_field_mapping_proposals
-- Additive only, idempotent, RLS protected, firm-scoped.

BEGIN;

-- ==============================================================
-- 1. doc_template_migration_runs
-- ==============================================================
CREATE TABLE IF NOT EXISTS doc_template_migration_runs (
  id SERIAL PRIMARY KEY,
  firm_id INTEGER NOT NULL,
  run_type TEXT NOT NULL DEFAULT 'bulk_field_migration',
  source_template_version TEXT,
  target_template_version TEXT,
  scope_filter_json JSONB,
  status TEXT NOT NULL DEFAULT 'queued',
  idempotency_key TEXT,
  requested_by_user_id INTEGER,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  total_templates_count INTEGER NOT NULL DEFAULT 0,
  templates_scanned_count INTEGER NOT NULL DEFAULT 0,
  proposals_generated_count INTEGER NOT NULL DEFAULT 0,
  proposals_accepted_count INTEGER NOT NULL DEFAULT 0,
  proposals_rejected_count INTEGER NOT NULL DEFAULT 0,
  proposals_applied_count INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  error_message TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  dry_run BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE doc_template_migration_runs IS 'Bulk template field migration run records. Each run scans templates, generates field mapping proposals, and tracks accept/reject/apply progress.';
COMMENT ON COLUMN doc_template_migration_runs.status IS 'queued | scanning | proposing | awaiting_review | applying | completed | partial_failure | failed';
COMMENT ON COLUMN doc_template_migration_runs.run_type IS 'bulk_field_migration | variable_rename | template_upgrade | clause_reindex';

CREATE INDEX IF NOT EXISTS idx_doc_tpl_mig_runs_firm
  ON doc_template_migration_runs(firm_id);
CREATE INDEX IF NOT EXISTS idx_doc_tpl_mig_runs_firm_status
  ON doc_template_migration_runs(firm_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_doc_tpl_mig_runs_firm_type
  ON doc_template_migration_runs(firm_id, run_type, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_doc_tpl_mig_runs_idempotency
  ON doc_template_migration_runs(firm_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ==============================================================
-- 2. doc_template_field_mapping_proposals
-- ==============================================================
CREATE TABLE IF NOT EXISTS doc_template_field_mapping_proposals (
  id SERIAL PRIMARY KEY,
  firm_id INTEGER NOT NULL,
  migration_run_id INTEGER NOT NULL REFERENCES doc_template_migration_runs(id) ON DELETE CASCADE,
  template_id INTEGER,
  template_name TEXT,
  source_field_key TEXT NOT NULL,
  source_field_label TEXT,
  source_field_type TEXT,
  target_case_field TEXT,
  target_variable_key TEXT,
  mapping_strategy TEXT DEFAULT 'auto_suggest',
  confidence_score TEXT,
  confidence_level TEXT DEFAULT 'medium',
  sample_values JSONB,
  transform_rule_json JSONB,
  review_status TEXT NOT NULL DEFAULT 'pending',
  reviewed_by_user_id INTEGER,
  reviewed_at TIMESTAMPTZ,
  applied BOOLEAN NOT NULL DEFAULT FALSE,
  applied_at TIMESTAMPTZ,
  applied_by_user_id INTEGER,
  idempotency_key TEXT,
  rejection_reason TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE doc_template_field_mapping_proposals IS 'Per-template, per-field mapping proposals generated by a migration run. Tracks accept/reject/apply decision lifecycle.';
COMMENT ON COLUMN doc_template_field_mapping_proposals.review_status IS 'pending | accepted | rejected | applied | superseded';
COMMENT ON COLUMN doc_template_field_mapping_proposals.mapping_strategy IS 'auto_suggest | exact_name | semantic_match | type_inference | manual_override';

CREATE INDEX IF NOT EXISTS idx_doc_tpl_map_prop_firm
  ON doc_template_field_mapping_proposals(firm_id);
CREATE INDEX IF NOT EXISTS idx_doc_tpl_map_prop_firm_run
  ON doc_template_field_mapping_proposals(firm_id, migration_run_id);
CREATE INDEX IF NOT EXISTS idx_doc_tpl_map_prop_firm_tpl
  ON doc_template_field_mapping_proposals(firm_id, template_id);
CREATE INDEX IF NOT EXISTS idx_doc_tpl_map_prop_firm_review
  ON doc_template_field_mapping_proposals(firm_id, review_status);
CREATE INDEX IF NOT EXISTS idx_doc_tpl_map_prop_firm_target
  ON doc_template_field_mapping_proposals(firm_id, target_case_field);

CREATE UNIQUE INDEX IF NOT EXISTS uq_doc_tpl_map_prop_idempotency
  ON doc_template_field_mapping_proposals(firm_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- ==============================================================
-- updated_at triggers
-- ==============================================================
DROP TRIGGER IF EXISTS trg_doc_tpl_mig_runs_updated_at ON doc_template_migration_runs;
CREATE OR REPLACE FUNCTION set_doc_tpl_mig_runs_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_doc_tpl_mig_runs_updated_at
BEFORE UPDATE ON doc_template_migration_runs
FOR EACH ROW EXECUTE FUNCTION set_doc_tpl_mig_runs_updated_at();

DROP TRIGGER IF EXISTS trg_doc_tpl_map_prop_updated_at ON doc_template_field_mapping_proposals;
CREATE OR REPLACE FUNCTION set_doc_tpl_map_prop_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_doc_tpl_map_prop_updated_at
BEFORE UPDATE ON doc_template_field_mapping_proposals
FOR EACH ROW EXECUTE FUNCTION set_doc_tpl_map_prop_updated_at();

-- ==============================================================
-- RLS: doc_template_migration_runs
-- ==============================================================
ALTER TABLE doc_template_migration_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE doc_template_migration_runs FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS doc_tpl_mig_runs_firm_select ON doc_template_migration_runs;
CREATE POLICY doc_tpl_mig_runs_firm_select ON doc_template_migration_runs
  FOR SELECT TO PUBLIC USING (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER);

DROP POLICY IF EXISTS doc_tpl_mig_runs_firm_insert ON doc_template_migration_runs;
CREATE POLICY doc_tpl_mig_runs_firm_insert ON doc_template_migration_runs
  FOR INSERT TO PUBLIC WITH CHECK (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER);

DROP POLICY IF EXISTS doc_tpl_mig_runs_firm_update ON doc_template_migration_runs;
CREATE POLICY doc_tpl_mig_runs_firm_update ON doc_template_migration_runs
  FOR UPDATE TO PUBLIC USING (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER)
  WITH CHECK (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER);

DO $$ BEGIN
  PERFORM 1
   WHERE EXISTS (
     SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'app_firms' AND table_name = 'rls_firms'
   )
     AND EXISTS (
       SELECT 1 FROM pg_proc p
       JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'app_firms' AND p.proname = 'enforce_company_id_v2'
     );
  IF FOUND THEN
    DROP POLICY IF EXISTS doc_tpl_mig_runs_company_rls ON doc_template_migration_runs;
    PERFORM app_firms.enforce_company_id_v2('doc_template_migration_runs', 'firm_id');
  END IF;
END $$;

-- ==============================================================
-- RLS: doc_template_field_mapping_proposals
-- ==============================================================
ALTER TABLE doc_template_field_mapping_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE doc_template_field_mapping_proposals FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS doc_tpl_map_prop_firm_select ON doc_template_field_mapping_proposals;
CREATE POLICY doc_tpl_map_prop_firm_select ON doc_template_field_mapping_proposals
  FOR SELECT TO PUBLIC USING (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER);

DROP POLICY IF EXISTS doc_tpl_map_prop_firm_insert ON doc_template_field_mapping_proposals;
CREATE POLICY doc_tpl_map_prop_firm_insert ON doc_template_field_mapping_proposals
  FOR INSERT TO PUBLIC WITH CHECK (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER);

DROP POLICY IF EXISTS doc_tpl_map_prop_firm_update ON doc_template_field_mapping_proposals;
CREATE POLICY doc_tpl_map_prop_firm_update ON doc_template_field_mapping_proposals
  FOR UPDATE TO PUBLIC USING (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER)
  WITH CHECK (firm_id = current_setting('app.current_firm_id', TRUE)::INTEGER);

DO $$ BEGIN
  PERFORM 1
   WHERE EXISTS (
     SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'app_firms' AND table_name = 'rls_firms'
   )
     AND EXISTS (
       SELECT 1 FROM pg_proc p
       JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'app_firms' AND p.proname = 'enforce_company_id_v2'
     );
  IF FOUND THEN
    DROP POLICY IF EXISTS doc_tpl_map_prop_company_rls ON doc_template_field_mapping_proposals;
    PERFORM app_firms.enforce_company_id_v2('doc_template_field_mapping_proposals', 'firm_id');
  END IF;
END $$;

GRANT SELECT, INSERT, UPDATE ON doc_template_migration_runs TO app_user;
GRANT SELECT, INSERT, UPDATE ON doc_template_field_mapping_proposals TO app_user;

COMMIT;
