export const HR_ERROR_CODES = {
  HR_PERMISSION_DENIED: "HR_PERMISSION_DENIED",
  HR_RECORD_CONFLICT: "HR_RECORD_CONFLICT",
  HR_INVALID_STATUS_TRANSITION: "HR_INVALID_STATUS_TRANSITION",
  HR_APPROVER_NOT_CONFIGURED: "HR_APPROVER_NOT_CONFIGURED",
  HR_PAYROLL_ALREADY_LOCKED: "HR_PAYROLL_ALREADY_LOCKED",
  HR_CLAIM_ALREADY_SENT_TO_ACCOUNTING: "HR_CLAIM_ALREADY_SENT_TO_ACCOUNTING",
  HR_EMPLOYEE_HAS_PENDING_HANDOVER: "HR_EMPLOYEE_HAS_PENDING_HANDOVER",
  HR_CROSS_FIRM_ACCESS_DENIED: "HR_CROSS_FIRM_ACCESS_DENIED",
  HR_METHOD_NOT_ALLOWED: "HR_METHOD_NOT_ALLOWED",
  HR_DOCUMENT_PERMISSION_DENIED: "HR_DOCUMENT_PERMISSION_DENIED",
  HR_IDEMPOTENCY_CONFLICT: "HR_IDEMPOTENCY_CONFLICT",
  HR_NOTICE_PERIOD_REQUIRED: "HR_NOTICE_PERIOD_REQUIRED",
  HR_APPROVAL_OVERDUE: "HR_APPROVAL_OVERDUE",
  HR_PAYROLL_PERIOD_DUPLICATE: "HR_PAYROLL_PERIOD_DUPLICATE",
  HR_LEAVE_INSUFFICIENT_BALANCE: "HR_LEAVE_INSUFFICIENT_BALANCE",
  HR_OUTSIDE_APPROVAL_WINDOW: "HR_OUTSIDE_APPROVAL_WINDOW",
  HR_SALARY_OUTSIDE_POLICY_RANGE: "HR_SALARY_OUTSIDE_POLICY_RANGE",
  HR_ATTENDANCE_OUTSIDE_GEOFENCE: "HR_ATTENDANCE_OUTSIDE_GEOFENCE",
  HR_ASSET_NOT_RETURNED: "HR_ASSET_NOT_RETURNED",
  HR_MODULE_DISABLED: "HR_MODULE_DISABLED",
  HR_SETTINGS_NOT_CONFIGURED: "HR_SETTINGS_NOT_CONFIGURED",
  HR_NOT_IMPLEMENTED: "HR_NOT_IMPLEMENTED",
  HR_DOCUMENT_EXPIRED: "HR_DOCUMENT_EXPIRED",
  HR_RECORD_VERSION_MISMATCH: "HR_RECORD_VERSION_MISMATCH",
  HR_DELEGATION_NOT_ACTIVE: "HR_DELEGATION_NOT_ACTIVE",
  HR_EMPLOYEE_NOT_FOUND: "HR_EMPLOYEE_NOT_FOUND",
  HR_REQUIRED_FIELD_MISSING: "HR_REQUIRED_FIELD_MISSING",
  HR_INVALID_FINAL_APPROVER_PARTNER: "INVALID_FINAL_APPROVER_PARTNER",
  HR_DELEGATION_CYCLE_DETECTED: "DELEGATION_CYCLE_DETECTED",
  HR_PAYROLL_PERIOD_LOCKED: "PAYROLL_PERIOD_LOCKED",
} as const;

export type HRErrorCode = (typeof HR_ERROR_CODES)[keyof typeof HR_ERROR_CODES];

export interface HRErrorShape {
  code: HRErrorCode;
  message: string;
  details?: unknown;
  httpStatus: number;
}

export class HRError extends Error {
  readonly code: HRErrorCode;
  readonly httpStatus: number;
  readonly details?: unknown;

  constructor(shape: HRErrorShape) {
    super(shape.message);
    this.name = "HRError";
    this.code = shape.code;
    this.httpStatus = shape.httpStatus;
    this.details = shape.details;
  }
}

export function createHRError(
  code: HRErrorCode,
  message: string,
  opts: { httpStatus?: number; details?: unknown } = {},
): HRError {
  const httpStatus = opts.httpStatus ?? inferHttpStatus(code);
  return new HRError({ code, message, httpStatus, details: opts.details });
}

function inferHttpStatus(code: HRErrorCode): number {
  switch (code) {
    case HR_ERROR_CODES.HR_MODULE_DISABLED:
      return 503;
    case HR_ERROR_CODES.HR_NOT_IMPLEMENTED:
      return 501;
    case HR_ERROR_CODES.HR_PERMISSION_DENIED:
    case HR_ERROR_CODES.HR_CROSS_FIRM_ACCESS_DENIED:
    case HR_ERROR_CODES.HR_DOCUMENT_PERMISSION_DENIED:
      return 403;
    case HR_ERROR_CODES.HR_RECORD_CONFLICT:
    case HR_ERROR_CODES.HR_IDEMPOTENCY_CONFLICT:
    case HR_ERROR_CODES.HR_INVALID_STATUS_TRANSITION:
    case HR_ERROR_CODES.HR_PAYROLL_ALREADY_LOCKED:
    case HR_ERROR_CODES.HR_CLAIM_ALREADY_SENT_TO_ACCOUNTING:
    case HR_ERROR_CODES.HR_EMPLOYEE_HAS_PENDING_HANDOVER:
    case HR_ERROR_CODES.HR_METHOD_NOT_ALLOWED:
    case HR_ERROR_CODES.HR_PAYROLL_PERIOD_DUPLICATE:
    case HR_ERROR_CODES.HR_LEAVE_INSUFFICIENT_BALANCE:
    case HR_ERROR_CODES.HR_OUTSIDE_APPROVAL_WINDOW:
    case HR_ERROR_CODES.HR_SALARY_OUTSIDE_POLICY_RANGE:
    case HR_ERROR_CODES.HR_ATTENDANCE_OUTSIDE_GEOFENCE:
    case HR_ERROR_CODES.HR_ASSET_NOT_RETURNED:
    case HR_ERROR_CODES.HR_DOCUMENT_EXPIRED:
    case HR_ERROR_CODES.HR_RECORD_VERSION_MISMATCH:
    case HR_ERROR_CODES.HR_DELEGATION_NOT_ACTIVE:
    case HR_ERROR_CODES.HR_NOTICE_PERIOD_REQUIRED:
      return 409;
    case HR_ERROR_CODES.HR_EMPLOYEE_NOT_FOUND:
      return 404;
    case HR_ERROR_CODES.HR_APPROVER_NOT_CONFIGURED:
    case HR_ERROR_CODES.HR_SETTINGS_NOT_CONFIGURED:
    case HR_ERROR_CODES.HR_REQUIRED_FIELD_MISSING:
      return 400;
    case HR_ERROR_CODES.HR_APPROVAL_OVERDUE:
      return 422;
    default:
      return 500;
  }
}

export function serializeHRError(err: unknown): { error: HRErrorShape } {
  if (err instanceof HRError) {
    return {
      error: { code: err.code, message: err.message, httpStatus: err.httpStatus, details: err.details },
    };
  }
  return {
    error: {
      code: HR_ERROR_CODES.HR_PERMISSION_DENIED,
      message: err instanceof Error ? err.message : "Unknown HR error",
      httpStatus: 500,
    },
  };
}
