import { pgTable, serial, text, integer, numeric, boolean, date, timestamp, index, uuid, jsonb } from "drizzle-orm/pg-core";

export const caseBillingEntriesTable = pgTable("case_billing_entries", {
  id:          serial("id").primaryKey(),
  caseId:      integer("case_id").notNull(),
  firmId:      integer("firm_id").notNull(),
  category:    text("category").notNull().default("disbursement"),
  description: text("description").notNull(),
  amount:      numeric("amount", { precision: 15, scale: 2 }).notNull(),
  quantity:    integer("quantity").notNull().default(1),
  isPaid:      boolean("is_paid").notNull().default(false),
  paidAt:      timestamp("paid_at", { withTimezone: true }),
  createdBy:   integer("created_by"),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:   timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmCaseIdx: index("idx_billing_entries_firm_case").on(t.firmId, t.caseId),
  caseIdx:     index("idx_billing_entries_case").on(t.caseId),
}));

export const invoicesTable = pgTable("invoices", {
  id:            serial("id").primaryKey(),
  firmId:        integer("firm_id").notNull(),
  caseId:        integer("case_id"),
  quotationId:   integer("quotation_id"),
  invoiceNo:     text("invoice_no").notNull(),
  status:        text("status").notNull().default("draft"),
  subtotal:      numeric("subtotal", { precision: 18, scale: 2 }).notNull().default("0"),
  taxTotal:      numeric("tax_total", { precision: 18, scale: 2 }).notNull().default("0"),
  grandTotal:    numeric("grand_total", { precision: 18, scale: 2 }).notNull().default("0"),
  amountPaid:    numeric("amount_paid", { precision: 18, scale: 2 }).notNull().default("0"),
  amountDue:     numeric("amount_due", { precision: 18, scale: 2 }).notNull().default("0"),
  issuedDate:    date("issued_date"),
  dueDate:       date("due_date"),
  notes:         text("notes"),
  version:       integer("version").notNull().default(0),
  deletedAt:     timestamp("deleted_at", { withTimezone: true }),
  createdBy:     integer("created_by"),
  createdAt:     timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:     timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmStatusIdx: index("idx_invoices_firm_status").on(t.firmId, t.status),
  dueDateIdx:    index("idx_invoices_due_date").on(t.dueDate),
  statusIdx:     index("idx_invoices_status").on(t.status),
}));

export const invoiceItemsTable = pgTable("invoice_items", {
  id:           serial("id").primaryKey(),
  invoiceId:    integer("invoice_id").notNull(),
  description:  text("description").notNull(),
  itemType:     text("item_type").notNull().default("disbursement"),
  itemCategory: text("item_category").notNull().default("fee"),
  amountExclTax: numeric("amount_excl_tax", { precision: 18, scale: 2 }).notNull().default("0"),
  taxRate:      numeric("tax_rate", { precision: 5, scale: 2 }).notNull().default("0"),
  taxAmount:    numeric("tax_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  amountInclTax: numeric("amount_incl_tax", { precision: 18, scale: 2 }).notNull().default("0"),
  sortOrder:    integer("sort_order").notNull().default(0),
}, (t) => ({
  invoiceIdIdx: index("idx_invoice_items_invoice").on(t.invoiceId),
}));

export const receiptsTable = pgTable("receipts", {
  id:            serial("id").primaryKey(),
  firmId:        integer("firm_id").notNull(),
  caseId:        integer("case_id"),
  invoiceId:     integer("invoice_id"),
  receiptNo:     text("receipt_no").notNull(),
  paymentMethod: text("payment_method").notNull().default("bank_transfer"),
  bankAccountId: integer("bank_account_id"),
  accountType:   text("account_type").notNull().default("client"),
  amount:        numeric("amount", { precision: 18, scale: 2 }).notNull(),
  receivedDate:  date("received_date").notNull(),
  referenceNo:   text("reference_no"),
  notes:         text("notes"),
  isReversed:    boolean("is_reversed").notNull().default(false),
  reversedBy:    integer("reversed_by"),
  reversedAt:    timestamp("reversed_at", { withTimezone: true }),
  createdBy:     integer("created_by"),
  createdAt:     timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  receivedDateIdx: index("idx_receipts_received_date").on(t.receivedDate),
  accountTypeIdx:  index("idx_receipts_account_type").on(t.firmId, t.accountType),
}));

export const receiptAllocationsTable = pgTable("receipt_allocations", {
  id:          serial("id").primaryKey(),
  receiptId:   integer("receipt_id").notNull(),
  invoiceId:   integer("invoice_id"),
  amount:      numeric("amount", { precision: 18, scale: 2 }).notNull(),
  notes:       text("notes"),
  createdAt:   timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  receiptIdx: index("idx_receipt_alloc_receipt").on(t.receiptId),
}));

export const paymentVouchersTable = pgTable("payment_vouchers", {
  id:                 serial("id").primaryKey(),
  firmId:             integer("firm_id").notNull(),
  caseId:             integer("case_id"),
  voucherType:        text("voucher_type").notNull().default("external_payment"),
  targetCaseId:       integer("target_case_id"),
  targetAccountId:    integer("target_account_id"),
  approvalStatus:     text("approval_status").notNull().default("approved"),
  isAdvance:          boolean("is_advance").notNull().default(false),
  approvedBy:         integer("approved_by"),
  voucherNo:          text("voucher_no").notNull(),
  clientRequestId:    text("client_request_id"),
  status:             text("status").notNull().default("pending_lawyer"),
  fundStatus:         text("fund_status").default("client_paid"),
  payeeName:          text("payee_name").notNull(),
  payeeBank:          text("payee_bank"),
  payeeAccountNo:     text("payee_account_no"),
  beneficiaryBank:    text("beneficiary_bank"),
  beneficiaryAccountNo: text("beneficiary_account_no"),
  paymentMethod:      text("payment_method").default("bank_transfer"),
  bankAccountId:      integer("bank_account_id"),
  accountType:        text("account_type").default("office"),
  bankChequeRefNo:    text("bank_cheque_ref_no"),
  amount:             numeric("amount", { precision: 18, scale: 2 }).notNull(),
  purpose:            text("purpose").notNull(),
  preparedBy:         integer("prepared_by"),
  preparedAt:         timestamp("prepared_at", { withTimezone: true }),
  lawyerApprovedBy:   integer("lawyer_approved_by"),
  lawyerApprovedAt:   timestamp("lawyer_approved_at", { withTimezone: true }),
  partnerApprovedBy:  integer("partner_approved_by"),
  partnerApprovedAt:  timestamp("partner_approved_at", { withTimezone: true }),
  receivedBy:         integer("received_by"),
  receivedAt:         timestamp("received_at", { withTimezone: true }),
  assignedAccountUserId: integer("assigned_account_user_id"),
  paymentDueAt:       timestamp("payment_due_at", { withTimezone: true }),
  slaPolicySnapshot:  jsonb("sla_policy_snapshot").$type<Record<string, unknown> | null>(),
  dueSoonNotifiedAt:  timestamp("due_soon_notified_at", { withTimezone: true }),
  overdueNotifiedAt:  timestamp("overdue_notified_at", { withTimezone: true }),
  breachedAt:         timestamp("breached_at", { withTimezone: true }),
  deadlineOverrideReason: text("deadline_override_reason"),
  deadlineOverriddenBy: integer("deadline_overridden_by"),
  deadlineOverriddenAt: timestamp("deadline_overridden_at", { withTimezone: true }),
  paidAmount:         numeric("paid_amount", { precision: 18, scale: 2 }),
  proofDocumentPath:  text("proof_document_path"),
  nextActionType:     text("next_action_type"),
  nextActionCustom:   text("next_action_custom"),
  nextActionRemarks:  text("next_action_remarks"),
  assignedClerkUserId: integer("assigned_clerk_user_id"),
  clerkActionExemptReason: text("clerk_action_exempt_reason"),
  lateCompletionReason: text("late_completion_reason"),
  paidAt:             timestamp("paid_at", { withTimezone: true }),
  paidBy:             integer("paid_by"),
  notes:              text("notes"),
  version:            integer("version").notNull().default(0),
  isReversed:         boolean("is_reversed").notNull().default(false),
  createdBy:          integer("created_by"),
  createdAt:          timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:          timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmStatusIdx: index("idx_pvouchers_firm_status").on(t.firmId, t.status),
  firmAssignedAccountIdx: index("idx_pvouchers_firm_assigned_account").on(t.firmId, t.assignedAccountUserId, t.status),
  firmDueAtIdx: index("idx_pvouchers_firm_due_at").on(t.firmId, t.paymentDueAt),
  firmReceivedAtIdx: index("idx_pvouchers_firm_received_at").on(t.firmId, t.receivedAt),
  firmAssignedClerkIdx: index("idx_pvouchers_firm_assigned_clerk").on(t.firmId, t.assignedClerkUserId, t.status),
}));

export const accountingSettingsTable = pgTable("accounting_settings", {
  firmId: integer("firm_id").primaryKey(),
  accountManagerRoleIds: jsonb("account_manager_role_ids").$type<number[]>().notNull().default([]),
  accountAdminRoleIds: jsonb("account_admin_role_ids").$type<number[]>().notNull().default([]),
  timezone: text("timezone").notNull().default("Asia/Kuala_Lumpur"),
  workingHoursStart: text("working_hours_start").notNull().default("09:00"),
  workingHoursEnd: text("working_hours_end").notNull().default("18:00"),
  excludeSaturday: boolean("exclude_saturday").notNull().default(true),
  excludeSunday: boolean("exclude_sunday").notNull().default(true),
  firmHolidays: jsonb("firm_holidays").$type<Array<{ date: string; label?: string }>>().notNull().default([]),
  approvalRules: jsonb("approval_rules").$type<Record<string, unknown>>().notNull().default({}),
  paymentVoucherSla: jsonb("payment_voucher_sla").$type<Record<string, unknown>>().notNull().default({}),
  clerkActionSla: jsonb("clerk_action_sla").$type<Record<string, unknown>>().notNull().default({}),
  paymentProofRequired: boolean("payment_proof_required").notNull().default(true),
  createdBy: integer("created_by"),
  updatedBy: integer("updated_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  timezoneIdx: index("idx_accounting_settings_timezone").on(t.timezone),
}));

export const paymentVoucherActionsTable = pgTable("payment_voucher_actions", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  paymentVoucherId: integer("payment_voucher_id").notNull(),
  caseId: integer("case_id"),
  assignedUserId: integer("assigned_user_id").notNull(),
  actionType: text("action_type").notNull(),
  customAction: text("custom_action"),
  status: text("status").notNull().default("assigned"),
  priority: text("priority").notNull().default("normal"),
  assignedAt: timestamp("assigned_at", { withTimezone: true }).notNull().defaultNow(),
  acknowledgeDueAt: timestamp("acknowledge_due_at", { withTimezone: true }),
  acknowledgedBy: integer("acknowledged_by"),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  completionDueAt: timestamp("completion_due_at", { withTimezone: true }),
  completedBy: integer("completed_by"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  completionNotes: text("completion_notes"),
  completionAttachmentPath: text("completion_attachment_path"),
  updatedMilestone: text("updated_milestone"),
  breachedAt: timestamp("breached_at", { withTimezone: true }),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  cancelledBy: integer("cancelled_by"),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmVoucherIdx: index("idx_payment_voucher_actions_firm_voucher").on(t.firmId, t.paymentVoucherId, t.status),
  firmAssignedIdx: index("idx_payment_voucher_actions_firm_assigned").on(t.firmId, t.assignedUserId, t.status),
  firmCaseIdx: index("idx_payment_voucher_actions_firm_case").on(t.firmId, t.caseId),
  firmCompletionDueIdx: index("idx_payment_voucher_actions_firm_completion_due").on(t.firmId, t.completionDueAt),
  firmAcknowledgeDueIdx: index("idx_payment_voucher_actions_firm_ack_due").on(t.firmId, t.acknowledgeDueAt),
}));

export const userNotificationsTable = pgTable("user_notifications", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  userId: integer("user_id").notNull(),
  sourceType: text("source_type").notNull(),
  sourceId: integer("source_id").notNull(),
  caseId: integer("case_id"),
  notificationType: text("notification_type").notNull(),
  title: text("title").notNull(),
  message: text("message"),
  meta: jsonb("meta").$type<Record<string, unknown> | null>(),
  isRead: boolean("is_read").notNull().default(false),
  readAt: timestamp("read_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmUserUnreadIdx: index("idx_user_notifications_firm_user_unread").on(t.firmId, t.userId, t.isRead, t.createdAt),
  firmUserTypeIdx: index("idx_user_notifications_firm_user_type").on(t.firmId, t.userId, t.notificationType, t.isRead),
  firmCaseIdx: index("idx_user_notifications_firm_case").on(t.firmId, t.caseId),
}));

export const paymentVoucherItemsTable = pgTable("payment_voucher_items", {
  id:          serial("id").primaryKey(),
  voucherId:   integer("voucher_id").notNull(),
  description: text("description").notNull(),
  itemType:    text("item_type").notNull().default("disbursement"),
  amount:      numeric("amount", { precision: 18, scale: 2 }).notNull(),
  sortOrder:   integer("sort_order").notNull().default(0),
}, (t) => ({
  voucherIdx: index("idx_pv_items_voucher").on(t.voucherId),
}));

export const ledgerEntriesTable = pgTable("ledger_entries", {
  id:           serial("id").primaryKey(),
  firmId:       integer("firm_id").notNull(),
  caseId:       integer("case_id"),
  entryDate:    date("entry_date").notNull(),
  entryType:    text("entry_type").notNull(),
  accountType:  text("account_type").notNull(),
  debit:        numeric("debit", { precision: 18, scale: 2 }).notNull().default("0"),
  credit:       numeric("credit", { precision: 18, scale: 2 }).notNull().default("0"),
  balanceAfter: numeric("balance_after", { precision: 18, scale: 2 }).notNull().default("0"),
  description:  text("description").notNull(),
  referenceNo:  text("reference_no"),
  sourceType:   text("source_type"),
  sourceId:     integer("source_id"),
  createdBy:    integer("created_by"),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  entryDateIdx:  index("idx_ledger_entry_date").on(t.firmId, t.entryDate),
  accountTypeIdx: index("idx_ledger_account_type").on(t.firmId, t.accountType),
}));

export const creditNotesTable = pgTable("credit_notes", {
  id:           serial("id").primaryKey(),
  firmId:       integer("firm_id").notNull(),
  caseId:       integer("case_id"),
  invoiceId:    integer("invoice_id"),
  creditNoteNo: text("credit_note_no").notNull(),
  reason:       text("reason").notNull(),
  amount:       numeric("amount", { precision: 18, scale: 2 }).notNull(),
  issuedDate:   date("issued_date").notNull(),
  notes:        text("notes"),
  createdBy:    integer("created_by"),
  createdAt:    timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmIdx:    index("idx_credit_notes_firm").on(t.firmId),
  invoiceIdx: index("idx_credit_notes_invoice").on(t.invoiceId),
}));

export const bankTransactionsTable = pgTable("bank_transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  firmId: integer("firm_id").notNull(),
  bankAccountId: integer("bank_account_id"),
  caseId: integer("case_id"),
  transactionDate: date("transaction_date").notNull(),
  description: text("description").notNull(),
  referenceNo: text("reference_no"),
  withdrawal: numeric("withdrawal", { precision: 12, scale: 2 }),
  deposit: numeric("deposit", { precision: 12, scale: 2 }),
  balance: numeric("balance", { precision: 12, scale: 2 }),
  isExported: boolean("is_exported").notNull().default(false),
  exportedAt: timestamp("exported_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmDateIdx: index("idx_bank_transactions_firm_date").on(t.firmId, t.transactionDate),
  exportIdx: index("idx_bank_transactions_export").on(t.firmId, t.isExported),
  firmAccountIdx: index("idx_bank_transactions_firm_account").on(t.firmId, t.bankAccountId),
  firmCaseIdx: index("idx_bank_transactions_firm_case").on(t.firmId, t.caseId),
}));

export const caseLedgersTable = pgTable("case_ledgers", {
  id: uuid("id").primaryKey().defaultRandom(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  transactionDate: date("transaction_date").notNull(),
  entryCategory: text("entry_category").notNull(),
  entryType: text("entry_type").notNull(),
  description: text("description").notNull(),
  amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
  sourceType: text("source_type"),
  sourceId: integer("source_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmCaseIdx: index("idx_case_ledgers_firm_case").on(t.firmId, t.caseId, t.transactionDate),
  firmCaseSourceIdx: index("idx_case_ledgers_source").on(t.firmId, t.caseId, t.sourceType, t.sourceId),
}));
