import { index, integer, jsonb, pgTable, serial, text, timestamp, boolean, uniqueIndex } from "drizzle-orm/pg-core";

export const communicationMailboxesTable = pgTable("communication_mailboxes", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  channel: text("channel").notNull(),
  provider: text("provider").notNull(),
  displayName: text("display_name"),
  address: text("address"),
  phoneNumber: text("phone_number"),
  mailboxType: text("mailbox_type").notNull().default("shared"),
  isActive: boolean("is_active").notNull().default(true),
  syncEnabled: boolean("sync_enabled").notNull().default(false),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdIdx: index("idx_communication_mailboxes_firm").on(t.firmId),
  firmChannelIdx: index("idx_communication_mailboxes_firm_channel").on(t.firmId, t.channel, t.isActive),
}));

export const communicationMessagesTable = pgTable("communication_messages", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  mailboxId: integer("mailbox_id"),
  channel: text("channel").notNull(),
  provider: text("provider").notNull(),
  providerMessageId: text("provider_message_id"),
  providerThreadId: text("provider_thread_id"),
  providerConversationId: text("provider_conversation_id"),
  providerFolder: text("provider_folder"),
  providerIsRead: boolean("provider_is_read").notNull().default(false),
  direction: text("direction").notNull(),
  fromAddress: text("from_address"),
  fromName: text("from_name"),
  toAddresses: jsonb("to_addresses").$type<string[]>().notNull().default([]),
  ccAddresses: jsonb("cc_addresses").$type<string[]>().notNull().default([]),
  bccAddresses: jsonb("bcc_addresses").$type<string[]>().notNull().default([]),
  subject: text("subject"),
  bodyText: text("body_text"),
  bodyHtml: text("body_html"),
  receivedAt: timestamp("received_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  internalStatus: text("internal_status").notNull().default("new"),
  isBatch: boolean("is_batch").notNull().default(false),
  batchOwnerUserId: integer("batch_owner_user_id"),
  linkedCaseId: integer("linked_case_id"),
  assignedToUserId: integer("assigned_to_user_id"),
  slaDueAt: timestamp("sla_due_at", { withTimezone: true }),
  lastActivityAt: timestamp("last_activity_at", { withTimezone: true }),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdIdx: index("idx_communication_messages_firm").on(t.firmId),
  firmStatusIdx: index("idx_communication_messages_firm_status").on(t.firmId, t.internalStatus, t.createdAt),
  firmAssignedIdx: index("idx_communication_messages_firm_assigned").on(t.firmId, t.assignedToUserId, t.createdAt),
  firmLinkedCaseIdx: index("idx_communication_messages_firm_case").on(t.firmId, t.linkedCaseId, t.createdAt),
  firmMailboxIdx: index("idx_communication_messages_firm_mailbox").on(t.firmId, t.mailboxId, t.createdAt),
  firmProviderThreadIdx: index("idx_communication_messages_firm_provider_thread").on(t.firmId, t.providerThreadId),
}));

export const communicationCaseTasksTable = pgTable("communication_case_tasks", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  parentMessageId: integer("parent_message_id").notNull(),
  channel: text("channel").notNull(),
  linkedCaseId: integer("linked_case_id"),
  caseRef: text("case_ref"),
  partyName: text("party_name"),
  bankRef: text("bank_ref"),
  developerRef: text("developer_ref"),
  propertyRef: text("property_ref"),
  responsibleLawyerId: integer("responsible_lawyer_id"),
  responsibleClerkId: integer("responsible_clerk_id"),
  assignedToUserId: integer("assigned_to_user_id"),
  assignedByUserId: integer("assigned_by_user_id"),
  assignedAt: timestamp("assigned_at", { withTimezone: true }),
  taskStatus: text("task_status").notNull().default("pending_owner_review"),
  requiredAction: text("required_action"),
  replyNote: text("reply_note"),
  internalNote: text("internal_note"),
  dueAt: timestamp("due_at", { withTimezone: true }),
  seenByOwnerAt: timestamp("seen_by_owner_at", { withTimezone: true }),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  readyAt: timestamp("ready_at", { withTimezone: true }),
  repliedAt: timestamp("replied_at", { withTimezone: true }),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdIdx: index("idx_communication_case_tasks_firm").on(t.firmId),
  firmParentIdx: index("idx_communication_case_tasks_parent").on(t.firmId, t.parentMessageId, t.createdAt),
  firmStatusIdx: index("idx_communication_case_tasks_status").on(t.firmId, t.taskStatus, t.createdAt),
  firmAssignedIdx: index("idx_communication_case_tasks_assigned").on(t.firmId, t.assignedToUserId, t.createdAt),
  firmCaseIdx: index("idx_communication_case_tasks_case").on(t.firmId, t.linkedCaseId, t.createdAt),
  firmDueIdx: index("idx_communication_case_tasks_due").on(t.firmId, t.dueAt),
}));

export const communicationDraftsTable = pgTable("communication_drafts", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  parentMessageId: integer("parent_message_id").notNull(),
  channel: text("channel").notNull(),
  draftType: text("draft_type").notNull(),
  status: text("status").notNull().default("draft"),
  toAddresses: jsonb("to_addresses").$type<string[]>().notNull().default([]),
  ccAddresses: jsonb("cc_addresses").$type<string[]>().notNull().default([]),
  bccAddresses: jsonb("bcc_addresses").$type<string[]>().notNull().default([]),
  subject: text("subject"),
  bodyText: text("body_text"),
  bodyHtml: text("body_html"),
  preparedByUserId: integer("prepared_by_user_id"),
  approvedByUserId: integer("approved_by_user_id"),
  sentByUserId: integer("sent_by_user_id"),
  preparedAt: timestamp("prepared_at", { withTimezone: true }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdIdx: index("idx_communication_drafts_firm").on(t.firmId),
  firmStatusIdx: index("idx_communication_drafts_firm_status").on(t.firmId, t.status, t.createdAt),
  firmParentIdx: index("idx_communication_drafts_parent").on(t.firmId, t.parentMessageId),
}));

export const communicationDraftTasksTable = pgTable("communication_draft_tasks", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  draftId: integer("draft_id").notNull(),
  caseTaskId: integer("case_task_id").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmIdIdx: index("idx_communication_draft_tasks_firm").on(t.firmId),
  draftIdIdx: index("idx_communication_draft_tasks_draft").on(t.draftId),
  caseTaskIdIdx: index("idx_communication_draft_tasks_task").on(t.caseTaskId),
  uniqDraftTask: uniqueIndex("uq_communication_draft_tasks_draft_task").on(t.draftId, t.caseTaskId),
}));

export const communicationAttachmentsTable = pgTable("communication_attachments", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  messageId: integer("message_id").notNull(),
  channel: text("channel").notNull(),
  filename: text("filename").notNull(),
  mimeType: text("mime_type"),
  sizeBytes: integer("size_bytes"),
  storagePath: text("storage_path"),
  providerAttachmentId: text("provider_attachment_id"),
  linkedCaseId: integer("linked_case_id"),
  savedToCaseDocumentId: integer("saved_to_case_document_id"),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmIdIdx: index("idx_communication_attachments_firm").on(t.firmId),
  messageIdIdx: index("idx_communication_attachments_message").on(t.messageId),
  caseIdIdx: index("idx_communication_attachments_case").on(t.linkedCaseId),
}));

export const communicationAuditLogsTable = pgTable("communication_audit_logs", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  messageId: integer("message_id"),
  caseTaskId: integer("case_task_id"),
  draftId: integer("draft_id"),
  actorUserId: integer("actor_user_id"),
  action: text("action").notNull(),
  oldValue: jsonb("old_value").$type<Record<string, unknown> | null>(),
  newValue: jsonb("new_value").$type<Record<string, unknown> | null>(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmIdIdx: index("idx_communication_audit_logs_firm").on(t.firmId, t.createdAt),
  messageIdx: index("idx_communication_audit_logs_message").on(t.firmId, t.messageId, t.createdAt),
  taskIdx: index("idx_communication_audit_logs_task").on(t.firmId, t.caseTaskId, t.createdAt),
  draftIdx: index("idx_communication_audit_logs_draft").on(t.firmId, t.draftId, t.createdAt),
}));

