import { pgTable, serial, text, integer, boolean, timestamp, index, date } from "drizzle-orm/pg-core";

export const documentTemplatesTable = pgTable("document_templates", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  name: text("name").notNull(),
  kind: text("kind").notNull().default("template"),
  documentType: text("document_type").notNull().default("other"),
  isActive: boolean("is_active").notNull().default(true),
  appliesToPurchaseMode: text("applies_to_purchase_mode"),
  appliesToTitleType: text("applies_to_title_type").notNull().default("any"),
  appliesToCaseType: text("applies_to_case_type"),
  documentGroup: text("document_group").notNull().default("Others"),
  sortOrder: integer("sort_order").notNull().default(0),
  description: text("description"),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name").notNull(),
  folderId: integer("folder_id"),
  mimeType: text("mime_type"),
  extension: text("extension"),
  fileSize: integer("file_size"),
  isTemplateCapable: boolean("is_template_capable").notNull().default(true),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdx: index("idx_doc_templates_firm").on(t.firmId),
  firmFolderIdx: index("idx_document_templates_firm_folder").on(t.firmId, t.folderId),
  firmKindIdx: index("idx_document_templates_firm_kind").on(t.firmId, t.kind),
  firmTemplateCapableIdx: index("idx_document_templates_template_capable").on(t.firmId, t.isTemplateCapable),
}));

export const caseDocumentsTable = pgTable("case_documents", {
  id: serial("id").primaryKey(),
  caseId: integer("case_id").notNull(),
  firmId: integer("firm_id").notNull(),
  templateId: integer("template_id"),
  templateSource: text("template_source"),
  platformDocumentId: integer("platform_document_id"),
  templateSnapshotName: text("template_snapshot_name"),
  templateSnapshotUpdatedAt: timestamp("template_snapshot_updated_at", { withTimezone: true }),
  name: text("name").notNull(),
  documentType: text("document_type").notNull().default("generated"),
  status: text("status").notNull().default("draft"),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name").notNull(),
  fileSize: integer("file_size"),
  isUploaded: boolean("is_uploaded").notNull().default(false),
  generatedBy: integer("generated_by"),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmCaseIdx: index("idx_case_docs_firm_case").on(t.firmId, t.caseId),
  caseIdx:     index("idx_case_docs_case").on(t.caseId),
  statusIdx:   index("idx_case_docs_status").on(t.status),
}));

export const caseWorkflowDocumentsTable = pgTable("case_workflow_documents", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  milestoneKey: text("milestone_key").notNull(),
  label: text("label").notNull(),
  dateValue: date("date_value"),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name").notNull(),
  mimeType: text("mime_type"),
  fileSize: integer("file_size"),
  uploadedBy: integer("uploaded_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => ({
  firmCaseIdx: index("idx_case_workflow_documents_firm_case").on(t.firmId, t.caseId),
  caseIdx: index("idx_case_workflow_documents_case").on(t.caseId),
  firmKeyIdx: index("idx_case_workflow_documents_firm_key").on(t.firmId, t.milestoneKey),
}));

export const caseLoanStampingItemsTable = pgTable("case_loan_stamping_items", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  itemKey: text("item_key").notNull(),
  customName: text("custom_name"),
  datedOn: date("dated_on"),
  stampedOn: date("stamped_on"),
  objectPath: text("object_path"),
  fileName: text("file_name"),
  mimeType: text("mime_type"),
  fileSize: integer("file_size"),
  uploadedBy: integer("uploaded_by"),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => ({
  firmCaseIdx: index("idx_case_loan_stamping_items_firm_case").on(t.firmId, t.caseId),
  caseIdx: index("idx_case_loan_stamping_items_case").on(t.caseId),
  firmKeyIdx: index("idx_case_loan_stamping_items_firm_key").on(t.firmId, t.itemKey),
  sortIdx: index("idx_case_loan_stamping_items_sort").on(t.firmId, t.caseId, t.sortOrder),
}));
