import { sql } from "drizzle-orm";
import { pgTable, serial, text, integer, boolean, timestamp, index, date, jsonb, uuid, uniqueIndex } from "drizzle-orm/pg-core";

export const documentTemplatesTable = pgTable("document_templates", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  name: text("name").notNull(),
  kind: text("kind").notNull().default("template"),
  documentType: text("document_type").notNull().default("other"),
  isActive: boolean("is_active").notNull().default(true),
  fileNamingRule: text("file_naming_rule"),
  clauseInsertionMode: text("clause_insertion_mode"),
  applicabilityMode: text("applicability_mode"),
  applicabilityRules: jsonb("applicability_rules"),
  appliesToPurchaseMode: text("applies_to_purchase_mode"),
  appliesToTitleType: text("applies_to_title_type").notNull().default("any"),
  appliesToCaseType: text("applies_to_case_type"),
  documentGroup: text("document_group").notNull().default("Others"),
  sortOrder: integer("sort_order").notNull().default(0),
  description: text("description"),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name").notNull(),
  folderId: integer("folder_id"),
  mimeType: text("mime_type"),
  extension: text("extension"),
  fileSize: integer("file_size"),
  isTemplateCapable: boolean("is_template_capable").notNull().default(true),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdx: index("idx_doc_templates_firm").on(t.firmId),
  firmFolderIdx: index("idx_document_templates_firm_folder").on(t.firmId, t.folderId),
  firmKindIdx: index("idx_document_templates_firm_kind").on(t.firmId, t.kind),
  firmTemplateCapableIdx: index("idx_document_templates_template_capable").on(t.firmId, t.isTemplateCapable),
}));

export const caseDocumentsTable = pgTable("case_documents", {
  id: serial("id").primaryKey(),
  caseId: integer("case_id").notNull(),
  firmId: integer("firm_id").notNull(),
  templateId: integer("template_id"),
  templateSource: text("template_source"),
  platformDocumentId: integer("platform_document_id"),
  templateSnapshotName: text("template_snapshot_name"),
  templateSnapshotUpdatedAt: timestamp("template_snapshot_updated_at", { withTimezone: true }),
  name: text("name").notNull(),
  documentType: text("document_type").notNull().default("generated"),
  status: text("status").notNull().default("draft"),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name").notNull(),
  fileSize: integer("file_size"),
  isUploaded: boolean("is_uploaded").notNull().default(false),
  generatedBy: integer("generated_by"),
  generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
  notes: text("notes"),
  clauseSnapshot: jsonb("clause_snapshot"),
  namingSnapshot: jsonb("naming_snapshot"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmCaseIdx: index("idx_case_docs_firm_case").on(t.firmId, t.caseId),
  caseIdx:     index("idx_case_docs_case").on(t.caseId),
  statusIdx:   index("idx_case_docs_status").on(t.status),
}));

export const caseWorkflowDocumentsTable = pgTable("case_workflow_documents", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  milestoneKey: text("milestone_key").notNull(),
  label: text("label").notNull(),
  dateValue: date("date_value"),
  objectPath: text("object_path").notNull(),
  fileName: text("file_name").notNull(),
  mimeType: text("mime_type"),
  fileSize: integer("file_size"),
  uploadedBy: integer("uploaded_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => ({
  firmCaseIdx: index("idx_case_workflow_documents_firm_case").on(t.firmId, t.caseId),
  caseIdx: index("idx_case_workflow_documents_case").on(t.caseId),
  firmKeyIdx: index("idx_case_workflow_documents_firm_key").on(t.firmId, t.milestoneKey),
}));

export const caseLoanStampingItemsTable = pgTable("case_loan_stamping_items", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  itemKey: text("item_key").notNull(),
  customName: text("custom_name"),
  datedOn: date("dated_on"),
  stampedOn: date("stamped_on"),
  objectPath: text("object_path"),
  fileName: text("file_name"),
  mimeType: text("mime_type"),
  fileSize: integer("file_size"),
  uploadedBy: integer("uploaded_by"),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
}, (t) => ({
  firmCaseIdx: index("idx_case_loan_stamping_items_firm_case").on(t.firmId, t.caseId),
  caseIdx: index("idx_case_loan_stamping_items_case").on(t.caseId),
  firmKeyIdx: index("idx_case_loan_stamping_items_firm_key").on(t.firmId, t.itemKey),
  sortIdx: index("idx_case_loan_stamping_items_sort").on(t.firmId, t.caseId, t.sortOrder),
}));

export const documentTemplateVersionsTable = pgTable("document_template_versions", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  templateId: integer("template_id").notNull(),
  versionNo: integer("version_no").notNull(),
  status: text("status").notNull().default("draft"),
  sourceObjectPath: text("source_object_path").notNull(),
  filename: text("filename").notNull(),
  mimeType: text("mime_type"),
  templateKind: text("template_kind"),
  category: text("category"),
  documentGroup: text("document_group"),
  variablesSnapshot: jsonb("variables_snapshot"),
  pdfMappingsSnapshot: jsonb("pdf_mappings_snapshot"),
  applicabilityRulesSnapshot: jsonb("applicability_rules_snapshot"),
  readinessRulesSnapshot: jsonb("readiness_rules_snapshot"),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  publishedBy: integer("published_by"),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  archivedBy: integer("archived_by"),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
}, (t) => ({
  firmIdx: index("idx_document_template_versions_firm").on(t.firmId),
  templateIdx: index("idx_document_template_versions_template").on(t.templateId),
  statusIdx: index("idx_document_template_versions_status").on(t.firmId, t.status),
  createdAtIdx: index("idx_document_template_versions_created_at").on(t.firmId, t.createdAt),
}));

export const documentGenerationRunsTable = pgTable("document_generation_runs", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  templateSource: text("template_source").notNull(),
  templateId: integer("template_id"),
  templateVersionId: integer("template_version_id"),
  platformDocumentId: integer("platform_document_id"),
  caseDocumentId: integer("case_document_id"),
  documentName: text("document_name").notNull(),
  renderMode: text("render_mode").notNull().default("docx"),
  status: text("status").notNull().default("pending"),
  renderedVariablesSnapshot: jsonb("rendered_variables_snapshot"),
  checklistSnapshot: jsonb("checklist_snapshot"),
  readinessSnapshot: jsonb("readiness_snapshot"),
  triggeredBy: integer("triggered_by"),
  triggeredAt: timestamp("triggered_at", { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmIdx: index("idx_document_generation_runs_firm").on(t.firmId),
  firmCaseIdx: index("idx_document_generation_runs_case").on(t.firmId, t.caseId),
  statusIdx: index("idx_document_generation_runs_status").on(t.firmId, t.status),
  triggeredAtIdx: index("idx_document_generation_runs_triggered_at").on(t.firmId, t.caseId, t.triggeredAt),
}));

export const documentBatchJobsTable = pgTable("document_batch_jobs", {
  id: uuid("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  jobType: text("job_type").notNull(),
  status: text("status").notNull().default("pending"),
  totalCount: integer("total_count").notNull().default(0),
  successCount: integer("success_count").notNull().default(0),
  failedCount: integer("failed_count").notNull().default(0),
  pendingCount: integer("pending_count").notNull().default(0),
  createdBy: integer("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  downloadObjectPath: text("download_object_path"),
  downloadFileName: text("download_file_name"),
  downloadMimeType: text("download_mime_type"),
  errorSummary: text("error_summary"),
}, (t) => ({
  firmIdx: index("idx_document_batch_jobs_firm").on(t.firmId),
  firmCaseIdx: index("idx_document_batch_jobs_case").on(t.firmId, t.caseId),
  statusIdx: index("idx_document_batch_jobs_status").on(t.firmId, t.status),
  createdAtIdx: index("idx_document_batch_jobs_created_at").on(t.firmId, t.createdAt),
}));

export const documentBatchJobItemsTable = pgTable("document_batch_job_items", {
  id: serial("id").primaryKey(),
  jobId: uuid("job_id").notNull(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  templateSource: text("template_source").notNull(),
  templateId: integer("template_id"),
  templateVersionId: integer("template_version_id"),
  platformDocumentId: integer("platform_document_id"),
  caseDocumentId: integer("case_document_id"),
  status: text("status").notNull().default("pending"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
}, (t) => ({
  jobIdx: index("idx_document_batch_job_items_job").on(t.jobId),
  firmIdx: index("idx_document_batch_job_items_firm").on(t.firmId),
  firmCaseIdx: index("idx_document_batch_job_items_case").on(t.firmId, t.caseId),
  statusIdx: index("idx_document_batch_job_items_status").on(t.firmId, t.status),
  createdAtIdx: index("idx_document_batch_job_items_created_at").on(t.firmId, t.caseId, t.createdAt),
}));

export const documentVariableDefinitionsTable = pgTable("document_variable_definitions", {
  id: serial("id").primaryKey(),
  key: text("key").notNull(),
  label: text("label").notNull(),
  description: text("description"),
  category: text("category").notNull().default("case"),
  valueType: text("value_type").notNull().default("string"),
  sourcePath: text("source_path"),
  formatter: text("formatter"),
  exampleValue: text("example_value"),
  isSystem: boolean("is_system").notNull().default(true),
  isActive: boolean("is_active").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  activeIdx: index("idx_document_variable_definitions_active").on(t.isActive, t.category, t.sortOrder, t.key),
}));

export const documentTemplateBindingsTable = pgTable("document_template_bindings", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id"),
  templateId: integer("template_id"),
  platformDocumentId: integer("platform_document_id"),
  variableKey: text("variable_key").notNull(),
  sourceMode: text("source_mode").notNull().default("registry_default"),
  sourcePath: text("source_path"),
  fixedValue: text("fixed_value"),
  formatterOverride: text("formatter_override"),
  isRequired: boolean("is_required").notNull().default(false),
  fallbackValue: text("fallback_value"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdx: index("idx_document_template_bindings_firm").on(t.firmId),
  firmTemplateIdx: index("idx_document_template_bindings_template").on(t.firmId, t.templateId),
  platformIdx: index("idx_document_template_bindings_platform").on(t.platformDocumentId),
  keyIdx: index("idx_document_template_bindings_key").on(t.firmId, t.variableKey),
}));

export const documentTemplateApplicabilityRulesTable = pgTable("document_template_applicability_rules", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id"),
  templateId: integer("template_id"),
  platformDocumentId: integer("platform_document_id"),
  isActive: boolean("is_active"),
  isRequired: boolean("is_required"),
  purchaseMode: text("purchase_mode"),
  titleType: text("title_type"),
  titleSubType: text("title_sub_type"),
  projectType: text("project_type"),
  developmentCondition: text("development_condition"),
  unitCategory: text("unit_category"),
  isTemplateCapable: boolean("is_template_capable"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdx: index("idx_document_template_applicability_rules_firm").on(t.firmId),
  firmTemplateIdx: index("idx_document_template_applicability_rules_template").on(t.firmId, t.templateId),
  platformIdx: index("idx_document_template_applicability_rules_platform").on(t.platformDocumentId),
}));

export const caseDocumentChecklistItemsTable = pgTable("case_document_checklist_items", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id").notNull(),
  checklistKey: text("checklist_key").notNull(),
  templateId: integer("template_id"),
  platformDocumentId: integer("platform_document_id"),
  caseDocumentId: integer("case_document_id"),
  label: text("label").notNull(),
  sourceType: text("source_type").notNull(),
  applicabilityResult: jsonb("applicability_result"),
  isRequired: boolean("is_required").notNull().default(false),
  status: text("status").notNull().default("pending"),
  notes: text("notes"),
  receivedAt: timestamp("received_at", { withTimezone: true }),
  receivedBy: integer("received_by"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  completedBy: integer("completed_by"),
  waivedAt: timestamp("waived_at", { withTimezone: true }),
  waivedBy: integer("waived_by"),
  waivedReason: text("waived_reason"),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  caseIdx: index("idx_case_document_checklist_items_case").on(t.firmId, t.caseId, t.sortOrder),
  statusIdx: index("idx_case_document_checklist_items_status").on(t.firmId, t.caseId, t.status),
}));

export const firmClausesTable = pgTable("firm_clauses", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  sourcePlatformClauseId: integer("source_platform_clause_id"),
  clauseCode: text("clause_code").notNull(),
  title: text("title").notNull(),
  category: text("category").notNull().default("General"),
  language: text("language").notNull().default("en"),
  body: text("body").notNull(),
  notes: text("notes"),
  tags: text("tags").array().notNull().default(sql`'{}'::text[]`),
  status: text("status").notNull().default("draft"),
  isSystem: boolean("is_system").notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  applicability: jsonb("applicability"),
  createdBy: integer("created_by"),
  updatedBy: integer("updated_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  codeUq: uniqueIndex("uq_firm_clauses_code").on(t.firmId, t.clauseCode),
  statusIdx: index("idx_firm_clauses_status").on(t.firmId, t.status),
  categoryIdx: index("idx_firm_clauses_category").on(t.firmId, t.category),
  languageIdx: index("idx_firm_clauses_language").on(t.firmId, t.language),
  tagsIdx: index("idx_firm_clauses_tags").using("gin", t.tags),
}));
