import { pgTable, serial, integer, text, timestamp, jsonb, boolean, index, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const fileCustodyItemsTable = pgTable("file_custody_items", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id"),
  projectId: integer("project_id"),
  matterLabel: text("matter_label").notNull().default("General"),
  fileReferenceNo: text("file_reference_no").notNull(),
  fileTitle: text("file_title").notNull(),
  fileDescription: text("file_description"),
  physicalOrDigital: text("physical_or_digital").notNull().default("digital"),
  category: text("category").notNull().default("court_document"),
  storageLocation: text("storage_location"),
  tags: text("tags"),
  currentHolderUserId: integer("current_holder_user_id"),
  currentHolderName: text("current_holder_name"),
  currentHolderContact: text("current_holder_contact"),
  currentHolderFirmExternal: text("current_holder_firm_external"),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  acknowledgeDueAt: timestamp("acknowledge_due_at", { withTimezone: true }),
  expectedReturnAt: timestamp("expected_return_at", { withTimezone: true }),
  lastMovementId: integer("last_movement_id"),
  lifecycleStatus: text("lifecycle_status").notNull().default("in_office"),
  statusSetAt: timestamp("status_set_at", { withTimezone: true }),
  isArchived: boolean("is_archived").notNull().default(false),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  archivedByUserId: integer("archived_by_user_id"),
  version: integer("version").notNull().default(0),
  meta: jsonb("meta").$type<Record<string, unknown> | null>(),
  createdByUserId: integer("created_by_user_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmFileRefUnique: uniqueIndex("uq_file_custody_items_firm_file_ref").on(t.firmId, t.fileReferenceNo),
  firmStatusIdx: index("idx_file_custody_items_firm_status").on(t.firmId, t.lifecycleStatus, sql`created_at DESC`),
  firmCaseIdx: index("idx_file_custody_items_firm_case").on(t.firmId, t.caseId),
  firmHolderIdx: index("idx_file_custody_items_firm_holder").on(t.firmId, t.currentHolderUserId),
  firmDueReturnIdx: index("idx_file_custody_items_firm_due_return").on(t.firmId, t.expectedReturnAt).where(sql`lifecycle_status IN ('out_on_loan','out_with_counsel','out_with_client','out_external')`),
  firmAckDueIdx: index("idx_file_custody_items_firm_ack_due").on(t.firmId, t.acknowledgeDueAt).where(sql`acknowledged_at IS NULL AND lifecycle_status != 'in_office'`),
  firmStatusSetIdx: index("idx_file_custody_items_firm_status_set").on(t.firmId, t.statusSetAt).where(sql`status_set_at IS NOT NULL`),
}));

export const fileCustodyMovementsTable = pgTable("file_custody_movements", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  custodyItemId: integer("custody_item_id").notNull(),
  movementKind: text("movement_kind").notNull(),
  fromHolderUserId: integer("from_holder_user_id"),
  fromHolderName: text("from_holder_name"),
  fromHolderContact: text("from_holder_contact"),
  fromHolderFirmExternal: text("from_holder_firm_external"),
  toHolderUserId: integer("to_holder_user_id"),
  toHolderName: text("to_holder_name"),
  toHolderContact: text("to_holder_contact"),
  toHolderFirmExternal: text("to_holder_firm_external"),
  expectedReturnAt: timestamp("expected_return_at", { withTimezone: true }),
  acknowledgeDueAt: timestamp("acknowledge_due_at", { withTimezone: true }),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  acknowledgedByUserId: integer("acknowledged_by_user_id"),
  acknowledgedNote: text("acknowledged_note"),
  returnedAt: timestamp("returned_at", { withTimezone: true }),
  returnedByUserId: integer("returned_by_user_id"),
  returnedCondition: text("returned_condition"),
  returnedNote: text("returned_note"),
  escalatedAt: timestamp("escalated_at", { withTimezone: true }),
  escalatedToPartner: boolean("escalated_to_partner").notNull().default(false),
  severity: text("severity").notNull().default("normal"),
  movementNote: text("movement_note"),
  meta: jsonb("meta").$type<Record<string, unknown> | null>(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdByUserId: integer("created_by_user_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmItemIdx: index("idx_file_custody_mv_firm_item_created").on(t.firmId, t.custodyItemId, sql`created_at DESC`),
  firmCreatedIdx: index("idx_file_custody_mv_firm_created").on(t.firmId, sql`created_at DESC`),
  firmAckPendingIdx: index("idx_file_custody_mv_firm_ack_pending").on(t.firmId, t.toHolderUserId, t.acknowledgeDueAt).where(sql`acknowledged_at IS NULL`),
  firmReturnPendingIdx: index("idx_file_custody_mv_firm_return_pending").on(t.firmId, t.expectedReturnAt).where(sql`returned_at IS NULL`),
  firmEscalatedIdx: index("idx_file_custody_mv_firm_escalated").on(t.firmId, t.escalatedAt).where(sql`escalated_at IS NOT NULL`),
}));
