import { pgTable, serial, integer, text, timestamp, jsonb, boolean, index, uniqueIndex, numeric } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const himsNotificationAuditTable = pgTable("hims_notification_audit", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  caseId: integer("case_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  notificationType: text("notification_type").notNull(),
  targetUserId: integer("target_user_id"),
  targetScope: text("target_scope").notNull().default("firm"),
  payloadJson: jsonb("payload_json"),
  severity: text("severity").default("info"),
  correlationId: text("correlation_id"),
  sourceSystem: text("source_system").notNull().default("HIMS"),
  sourceEventName: text("source_event_name"),
  sourceEventRef: text("source_event_ref"),
  notificationCreated: boolean("notification_created").notNull().default(false),
  notificationId: integer("notification_id"),
  deduplicated: boolean("deduplicated").notNull().default(false),
  deduplicatedAgainstId: integer("deduplicated_against_id"),
  deliveryCount: integer("delivery_count").notNull().default(0),
  lastDeliveryAttemptAt: timestamp("last_delivery_attempt_at", { withTimezone: true }),
  lastDeliveryError: text("last_delivery_error"),
  actorUserId: integer("actor_user_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdx: index("idx_hims_notif_audit_firm").on(t.firmId),
  firmCaseIdx: index("idx_hims_notif_audit_firm_case").on(t.firmId, t.caseId),
  uqIdem: uniqueIndex("uq_hims_notif_audit_idem").on(t.firmId, t.idempotencyKey),
}));

export const communicationCaseTaskLinkAuditTable = pgTable("communication_case_task_link_audit", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  messageId: integer("message_id").notNull(),
  caseTaskId: integer("case_task_id"),
  caseId: integer("case_id").notNull(),
  actionType: text("action_type").notNull().default("LINK_TASK"),
  beforeAssignedToUserId: integer("before_assigned_to_user_id"),
  afterAssignedToUserId: integer("after_assigned_to_user_id"),
  beforeTaskStatus: text("before_task_status"),
  afterTaskStatus: text("after_task_status"),
  beforeRequiredAction: text("before_required_action"),
  afterRequiredAction: text("after_required_action"),
  beforeDueAt: timestamp("before_due_at", { withTimezone: true }),
  afterDueAt: timestamp("after_due_at", { withTimezone: true }),
  readToggledOnMessage: boolean("read_toggled_on_message").notNull().default(false),
  idempotencyKey: text("idempotency_key"),
  actorUserId: integer("actor_user_id"),
  actorRole: text("actor_role"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  firmIdx: index("idx_comm_task_link_audit_firm").on(t.firmId),
  firmMsgIdx: index("idx_comm_task_link_audit_msg").on(t.firmId, t.messageId),
  firmCaseIdx: index("idx_comm_task_link_audit_case").on(t.firmId, t.caseId),
  uqIdem: uniqueIndex("uq_comm_task_link_audit_idem").on(t.firmId, t.idempotencyKey).where(sql`idempotency_key IS NOT NULL`),
}));

export const einvoiceSubmissionAuditTable = pgTable("einvoice_submission_audit", {
  id: serial("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  invoiceId: integer("invoice_id").notNull(),
  integrationId: integer("integration_id"),
  actionType: text("action_type").notNull().default("SUBMIT"),
  submissionStatus: text("submission_status").notNull().default("BOUNDARY_CHECK"),
  boundaryPassed: boolean("boundary_passed").notNull().default(false),
  boundaryErrorCode: text("boundary_error_code"),
  boundaryErrorMessage: text("boundary_error_message"),
  provider: text("provider"),
  einvoiceIntegrationStatus: text("einvoice_integration_status"),
  idempotencyKey: text("idempotency_key"),
  submissionRequestJson: jsonb("submission_request_json"),
  submissionResponseJson: jsonb("submission_response_json"),
  externalSubmissionUid: text("external_submission_uid"),
  externalEinvoiceUuid: text("external_einvoice_uuid"),
  externalStatusUrl: text("external_status_url"),
  externalQrCodeData: text("external_qr_code_data"),
  requestSentAt: timestamp("request_sent_at", { withTimezone: true }),
  responseReceivedAt: timestamp("response_received_at", { withTimezone: true }),
  retryAttempt: integer("retry_attempt").notNull().default(0),
  scheduledRetryAt: timestamp("scheduled_retry_at", { withTimezone: true }),
  actorUserId: integer("actor_user_id"),
  actorRole: text("actor_role"),
  clientRequestId: text("client_request_id"),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  invoiceNoSnapshot: text("invoice_no_snapshot"),
  grandTotalSnapshot: numeric("grand_total_snapshot", { precision: 20, scale: 2 }),
  invoiceStatusSnapshot: text("invoice_status_snapshot"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmIdx: index("idx_einvoice_sub_audit_firm").on(t.firmId),
  firmInvoiceIdx: index("idx_einvoice_sub_audit_firm_invoice").on(t.firmId, t.invoiceId),
  firmStatusIdx: index("idx_einvoice_sub_audit_firm_status").on(t.firmId, t.submissionStatus, t.createdAt),
  uqIdem: uniqueIndex("uq_einvoice_sub_audit_idem").on(t.firmId, t.idempotencyKey).where(sql`idempotency_key IS NOT NULL`),
}));
