import { pgTable, serial, text, integer, boolean, timestamp, jsonb, uuid, index, uniqueIndex } from "drizzle-orm/pg-core";

export const platformSnapshotsTable = pgTable("platform_snapshots", {
  id: uuid("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  snapshotType: text("snapshot_type").notNull(),
  scopeType: text("scope_type").notNull(),
  moduleCode: text("module_code"),
  targetEntityType: text("target_entity_type"),
  targetEntityId: text("target_entity_id"),
  targetLabel: text("target_label"),
  triggerType: text("trigger_type").notNull(),
  triggerActionCode: text("trigger_action_code"),
  createdByUserId: integer("created_by_user_id"),
  createdByEmail: text("created_by_email"),
  reason: text("reason"),
  note: text("note"),
  status: text("status").notNull().default("completed"),
  integrityStatus: text("integrity_status").notNull().default("unverified"),
  schemaVersion: text("schema_version"),
  appVersion: text("app_version"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  failedAt: timestamp("failed_at", { withTimezone: true }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  retentionPolicyCode: text("retention_policy_code"),
  pinnedAt: timestamp("pinned_at", { withTimezone: true }),
  pinnedBy: integer("pinned_by"),
  pinnedReason: text("pinned_reason"),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  deletedBy: integer("deleted_by"),
  deletedReason: text("deleted_reason"),
  sizeBytes: integer("size_bytes"),
  storageDriver: text("storage_driver").notNull().default("db"),
  storagePath: text("storage_path"),
  payloadStorageKey: text("payload_storage_key"),
  payloadJson: jsonb("payload_json"),
  itemCountsJson: jsonb("item_counts_json"),
  metadataJson: jsonb("metadata_json"),
  checksum: text("checksum"),
  restorable: boolean("restorable").notNull().default(true),
  restoreNotes: text("restore_notes"),
  lastAccessedAt: timestamp("last_accessed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmCreatedIdx: index("idx_platform_snapshots_firm_created_at").on(t.firmId, t.createdAt),
  typeCreatedIdx: index("idx_platform_snapshots_type_created_at").on(t.snapshotType, t.createdAt),
  moduleCreatedIdx: index("idx_platform_snapshots_module_created_at").on(t.moduleCode, t.createdAt),
  targetIdx: index("idx_platform_snapshots_target").on(t.targetEntityType, t.targetEntityId),
  triggerIdx: index("idx_platform_snapshots_trigger").on(t.triggerType, t.createdAt),
  statusIdx: index("idx_platform_snapshots_status").on(t.status, t.createdAt),
  pinnedIdx: index("idx_platform_snapshots_pinned_at").on(t.firmId, t.pinnedAt),
  deletedIdx: index("idx_platform_snapshots_deleted_at").on(t.firmId, t.deletedAt),
  codeUq: uniqueIndex("uq_platform_snapshots_storage_key").on(t.payloadStorageKey),
}));

export const platformSnapshotItemsTable = pgTable("platform_snapshot_items", {
  id: serial("id").primaryKey(),
  snapshotId: uuid("snapshot_id").notNull(),
  firmId: integer("firm_id").notNull(),
  itemType: text("item_type").notNull(),
  itemId: text("item_id"),
  itemLabel: text("item_label"),
  moduleCode: text("module_code"),
  stateHash: text("state_hash"),
  payloadFragment: jsonb("payload_fragment"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  snapshotIdx: index("idx_platform_snapshot_items_snapshot").on(t.snapshotId),
  firmTypeIdx: index("idx_platform_snapshot_items_firm_type").on(t.firmId, t.itemType),
  itemLookupIdx: index("idx_platform_snapshot_items_item").on(t.itemType, t.itemId),
}));

export const platformMaintenanceActionsTable = pgTable("platform_maintenance_actions", {
  id: uuid("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  actionCode: text("action_code").notNull(),
  scopeType: text("scope_type").notNull(),
  moduleCode: text("module_code"),
  targetEntityType: text("target_entity_type"),
  targetEntityId: text("target_entity_id"),
  targetLabel: text("target_label"),
  riskLevel: text("risk_level").notNull(),
  status: text("status").notNull(),
  requiresSnapshot: boolean("requires_snapshot").notNull().default(false),
  preActionSnapshotId: uuid("pre_action_snapshot_id"),
  approvalRequestId: uuid("approval_request_id"),
  reason: text("reason").notNull(),
  typedConfirmation: text("typed_confirmation"),
  stepUpConfirmation: text("step_up_confirmation"),
  previewPayload: jsonb("preview_payload"),
  executionPayload: jsonb("execution_payload"),
  resultPayload: jsonb("result_payload"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedByUserId: integer("requested_by_user_id").notNull(),
  requestedByEmail: text("requested_by_email"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  failedAt: timestamp("failed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmCreatedIdx: index("idx_platform_maint_actions_firm_created_at").on(t.firmId, t.createdAt),
  codeCreatedIdx: index("idx_platform_maint_actions_code_created_at").on(t.actionCode, t.createdAt),
  statusCreatedIdx: index("idx_platform_maint_actions_status_created_at").on(t.status, t.createdAt),
  targetIdx: index("idx_platform_maint_actions_target").on(t.targetEntityType, t.targetEntityId),
  snapshotIdx: index("idx_platform_maint_actions_snapshot").on(t.preActionSnapshotId),
  approvalIdx: index("idx_platform_maint_actions_approval_request").on(t.approvalRequestId),
}));

export const platformMaintenanceActionStepsTable = pgTable("platform_maintenance_action_steps", {
  id: serial("id").primaryKey(),
  actionId: uuid("action_id").notNull(),
  stepCode: text("step_code").notNull(),
  stepOrder: integer("step_order").notNull().default(0),
  status: text("status").notNull().default("queued"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  resultPayload: jsonb("result_payload"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  actionIdx: index("idx_platform_maint_action_steps_action").on(t.actionId),
  statusIdx: index("idx_platform_maint_action_steps_status").on(t.status),
}));

export const platformRestoreActionsTable = pgTable("platform_restore_actions", {
  id: uuid("id").primaryKey(),
  firmId: integer("firm_id").notNull(),
  snapshotId: uuid("snapshot_id").notNull(),
  restoreScopeType: text("restore_scope_type").notNull(),
  moduleCode: text("module_code"),
  targetEntityType: text("target_entity_type"),
  targetEntityId: text("target_entity_id"),
  targetLabel: text("target_label"),
  riskLevel: text("risk_level").notNull(),
  status: text("status").notNull(),
  approvalRequestId: uuid("approval_request_id"),
  reason: text("reason").notNull(),
  typedConfirmation: text("typed_confirmation"),
  stepUpConfirmation: text("step_up_confirmation"),
  previewPayload: jsonb("preview_payload"),
  executionPayload: jsonb("execution_payload"),
  resultPayload: jsonb("result_payload"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  requestedByUserId: integer("requested_by_user_id").notNull(),
  requestedByEmail: text("requested_by_email"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  failedAt: timestamp("failed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  firmCreatedIdx: index("idx_platform_restore_actions_firm_created_at").on(t.firmId, t.createdAt),
  snapshotIdx: index("idx_platform_restore_actions_snapshot").on(t.snapshotId),
  statusCreatedIdx: index("idx_platform_restore_actions_status_created_at").on(t.status, t.createdAt),
  targetIdx: index("idx_platform_restore_actions_target").on(t.targetEntityType, t.targetEntityId),
  approvalIdx: index("idx_platform_restore_actions_approval_request").on(t.approvalRequestId),
}));

export const platformRestoreActionStepsTable = pgTable("platform_restore_action_steps", {
  id: serial("id").primaryKey(),
  restoreActionId: uuid("restore_action_id").notNull(),
  stepCode: text("step_code").notNull(),
  stepOrder: integer("step_order").notNull().default(0),
  status: text("status").notNull().default("queued"),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  resultPayload: jsonb("result_payload"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  actionIdx: index("idx_platform_restore_action_steps_action").on(t.restoreActionId),
  statusIdx: index("idx_platform_restore_action_steps_status").on(t.status),
}));

export const platformSnapshotRetentionPoliciesTable = pgTable("platform_snapshot_retention_policies", {
  code: text("code").primaryKey(),
  label: text("label").notNull(),
  retentionDays: integer("retention_days").notNull(),
  isProtected: boolean("is_protected").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (t) => ({
  retentionIdx: index("idx_platform_snapshot_retention_days").on(t.retentionDays),
}));

export const PLATFORM_SNAPSHOT_DEFAULT_POLICY_CODE = "scheduled_daily";

export const platformSnapshotPolicySeed = [
  { code: "pre_action", label: "Pre-action snapshots", retentionDays: 30, isProtected: false },
  { code: "pre_restore", label: "Pre-restore snapshots", retentionDays: 30, isProtected: false },
  { code: "manual", label: "Manual snapshots", retentionDays: 90, isProtected: false },
  { code: "scheduled_daily", label: "Scheduled daily snapshots", retentionDays: 14, isProtected: false },
  { code: "scheduled_weekly", label: "Scheduled weekly snapshots", retentionDays: 56, isProtected: false },
  { code: "scheduled_monthly", label: "Scheduled monthly snapshots", retentionDays: 180, isProtected: false },
  { code: "incident_recovery", label: "Incident recovery snapshots", retentionDays: 180, isProtected: true },
  { code: "system_baseline", label: "System baseline snapshots", retentionDays: 180, isProtected: true },
] as const;

export function computeExpiresAt(createdAt: Date, retentionDays: number): Date {
  return new Date(createdAt.getTime() + retentionDays * 24 * 60 * 60 * 1000);
}
