import { pgTable, serial, text, integer, numeric, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";

export const quotationsTable = pgTable("quotations", {
  id:                      serial("id").primaryKey(),
  firmId:                  integer("firm_id").notNull(),
  caseId:                  integer("case_id"),
  referenceNo:             text("reference_no").notNull(),
  stNo:                    text("st_no"),
  clientName:              text("client_name").notNull(),
  propertyDescription:     text("property_description"),
  purchasePrice:           numeric("purchase_price", { precision: 18, scale: 2 }),
  bankName:                text("bank_name"),
  loanAmount:              text("loan_amount"),
  loanAmountNum:           numeric("loan_amount_num", { precision: 18, scale: 2 }),
  ruleVersionId:           integer("rule_version_id"),
  status:                  text("status").notNull().default("draft"),
  notes:                   text("notes"),
  feeOverrideReason:       text("fee_override_reason"),
  feeOverrideApprovedBy:   integer("fee_override_approved_by"),
  acceptedAt:              timestamp("accepted_at", { withTimezone: true }),
  sentAt:                  timestamp("sent_at", { withTimezone: true }),
  createdBy:               integer("created_by"),
  createdAt:               timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt:               timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const quotationItemsTable = pgTable("quotation_items", {
  id:              serial("id").primaryKey(),
  quotationId:     integer("quotation_id").notNull(),
  section:         text("section").notNull(),
  category:        text("category"),
  itemNo:          text("item_no"),
  subItemNo:       text("sub_item_no"),
  description:     text("description").notNull(),
  taxCode:         text("tax_code").notNull().default("T"),
  amountExclTax:   numeric("amount_excl_tax", { precision: 18, scale: 2 }).notNull().default("0"),
  taxRate:         numeric("tax_rate", { precision: 5, scale: 2 }).notNull().default("8"),
  taxAmount:       numeric("tax_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  amountInclTax:   numeric("amount_incl_tax", { precision: 18, scale: 2 }).notNull().default("0"),
  isSystemGenerated: boolean("is_system_generated").notNull().default(false),
  itemType:        text("item_type").notNull().default("disbursement"),
  sortOrder:       integer("sort_order").notNull().default(0),
  createdAt:       timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
